### ISSUE TITLE
Handle specific reasons of HttpMessageNotReadableException

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#1]
Something like this

```java
    @ExceptionHandler
    public ResponseEntity<Problem> onHttpMessageNotReadable(final HttpMessageNotReadableException e) throws Throwable {
        final Throwable cause = e.getCause();
        if (cause == null) {
            return onException(e);
        } else if (cause instanceof JsonParseException) {
            return onParseException((JsonParseException) cause);
        } else if (cause instanceof JsonMappingException) {
            return onMappingException((JsonMappingException) cause);
        } else {
             ...
        }
    }
```

**Comment by jhorstmann** [comment]
+1, I had difficulty debugging a case where reading failed because my `@JsonCreator` annotations were wrong or missing after content-type and json type dispatching already worked. A more specific exception would have been nice for that case.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Alternatively you can throw and catch it. So you don't need the instanceof checks.

**Comment by lukasniemeier-zalando** [comment]
> Alternatively you can throw and catch it. So you don't need the instanceof checks.

If you throw an exception from a ``ExceptionHandler``, will it be catched by any ``ControllerAdvice`` again? I think I've seen ``JsonParseException`` (not wrapped inside a ``HttpMessageNotReadableException``), which would be cool for this.

**Comment by whiskeysierra** [comment]
I was thinking of throwing and catching within the same method. But
throwing from one handler to another would be awesome.

**Comment by lukasniemeier-zalando** [comment]
I took another look: throwing from one handler to another seems to be not possible (without crazy hacks). On the other hand I couldn't reproduce to provoke a `JsonParseException` not wrapped inside a `HttpMessageNotReadableException`. So we should start without that.

* The `HttpMessageNotReadableException` itself does not contain anything interesting for the user
* The `cause` of the `HttpMessageNotReadableException` can (at least) be `JsonProcessingException`, `JsonParseException`, `JsonMappingException` or `InvalidFormatException`
* Sometimes there is valuable information in the _cause_ of the `cause` (let's call it `rootCause'), e.g. in case you have an actual syntax error in your JSON the outer `cause` (`JsonMappingException`) will not contain any parser location information but `rootCause` (`JsonParseException`) does

I'm not decide on when to pick `400` vs. `422`. 
* `InvalidFormatException` seems to be only thrown in case of valid JSON but mismatching/malformed type -> `422`
* `JsonMappingException` one would have to look at the `rootCause`; in case of `JsonParseException` it's a syntax error -> `400`, otherwise -> `422`? E.g. with Jackson you'll get a `DateTimeParseException` wrapped inside a `JsonMappingException` if you specify a time string that does not parse (depending on your configuration) - should this be a `422` because it's still valid JSON?
* The rest should be only syntax related -> `400`

**Comment by whiskeysierra** [comment]
Ok, so the only thing that is workable for now would be to handle `HttpMessageNotReadableException` and inspect the root cause, e.g. like this:

```java
public ResponseEntity<Problem> onHttpMessageNotReadable(..) {
    try {
        throw Throwables.getRootCause(e); // from Guava
    } catch (JsonProcessingException ..) {
        // ...
    } catch (JsonParseException ..) {

    } catch (..) {

    }
}
```

Regarding the status code, I'd agree with the proposed solution.

**Comment by lukasniemeier-zalando** [comment]
I'd still make use of potential fields of the outer `cause` (e.g. `JsonMappingException` with a `JsonParseException` we could leverage the `path` if available).

I will try to prepare a PR.

**Comment by whiskeysierra** [comment]
> I'd still make use of potential fields of the outer cause (e.g. JsonMappingException with a JsonParseException we could leverage the path if available).

Absolutely. Should we include stuff like this as separate properties in the problem even?

**Comment by lukasniemeier-zalando** [comment]
@whiskeysierra that's what I am trying right now yep

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando Are you still working on this?

**Comment by lukasniemeier-zalando** [comment]
I think I am close to a solution - it may take me another 9 months!

No right now I am not but IMO the issue has a right to stay (in whatever form).

**Comment by timothy-mugayi** [comment]
Any updates on this?

**Comment by whiskeysierra** [comment]
@timothy-mugayi What are you hoping for?

**Comment by timothy-mugayi** [comment]
I was hoping there was a more elegant way of hanlding exceptions instead of having to do below 

```
@ExceptionHandler
    public ResponseEntity<Problem> onHttpMessageNotReadable(final HttpMessageNotReadableException e) throws Throwable {
        final Throwable cause = e.getCause();
        if (cause == null) {
            return onException(e);
        } else if (cause instanceof JsonParseException) {
            return onParseException((JsonParseException) cause);
        } else if (cause instanceof JsonMappingException) {
            return onMappingException((JsonMappingException) cause);
        } else {
             ...
        }
    }
```
