### ISSUE TITLE
Make TYPE_VALUE customizable

### ISSUE THREAD

**Issue by sta-szek** [zalando/problem-spring-web#100]
Currently there is no (easy) way to replace zalando's `TYPE_VALUE`'s e.g.:
`public static final String TYPE_VALUE = "https://zalando.github.io/problem/constraint-violation";`

Why?
I want custom problem description for my developers / end users

**Comment by whiskeysierra** [comment]
@sta-szek I released 0.19.0

**Comment by sta-szek** [comment]
@whiskeysierra thanks a lot!
