### ISSUE TITLE
Make ConstraintViolationProblem more customizable

### ISSUE THREAD

**Issue by sta-szek** [zalando/problem-spring-web#102]
Currently we can customize `defaultConstraintViolationType`, `defaultConstraintViolationStatus` or `formatFieldName`, but I think that customization of `violations` is missing.
It would be nice if I could rename [`violations` field](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/ConstraintViolationProblem.java#L20) and also [fields in `Violation` class](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/Violation.java#L8-L9).

I think the best way is to make [defaultConstraintViolationProblem](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/BaseValidationAdviceTrait.java#L48) similar to [defaultConstraintViolationType](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/BaseValidationAdviceTrait.java#L19).
Moreover we must provide `violations` preprocessing ([probably in here](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/BaseValidationAdviceTrait.java#L45)) similar to [this one ](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L216) as it would provide possibility to change `Violation` class to my custom one.

To acheive this [Violation](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/Violation.java) and [ConstraintViolationProblem](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/ConstraintViolationProblem.java) should not be final.

The final result should allow me to make structure as follows:
```
"validation-errors": [
    {
      "context-key": "fieldName",
      "message-key": "not-null"
    }
]
```

**Comment by whiskeysierra** [comment]
@sta-szek Have you considered to user https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations for this?

**Comment by whiskeysierra** [comment]
> To acheive this Violation and ConstraintViolationProblem should not be final.

I'd rather introduce an interface for them. 

In general, I feel a use case like this is achieved in a simpler way by allowing to replace the whole problem instance completely, e.g. by just overridding `BaseValidationAdviceTrait#newConstraintViolationProblem` and calling `super.newConstraintViolationProblem` before modifying the result.

**Comment by sta-szek** [comment]
I tried second way but `JacksonMixInAnnotations` looks prettier - less code :)
@whiskeysierra thanks.

**Comment by sta-szek** [comment]
@whiskeysierra what about adding additional parameters in validation errors (violations) e.g.:
```
"validation-errors": [
    {
      "context-key": "size",
      "message-key": "out-of-range"
      "params": {
              "min": "1",
              "max": "2"
        }
    }
]
```

We would like to use those parameters on frontend while end-user message formatting.
BTW `ConstraintViolationProblem` could have additional constructor parameter - `title` and I think it should be taken from `defaultConstraintViolationTitle` method, as we change vocabulary from `violations` to `validation-errors`

**Comment by whiskeysierra** [comment]
I'd suggest to use a completely different class-(hierarchy) that has nothing to do with ContraintViolationProblem and Violation. There is not so much code that both cases share actually. Have you considered implementing this yourself?

**Comment by sta-szek** [comment]
Yes but implementing by myself means I have to maintain this code :)
`JacksonMixInAnnotations` is enough for me. Thanks for help

**Comment by whiskeysierra** [comment]
> Yes but implementing by myself means I have to maintain this code :)

That is true, but on the other hand you also have the full freedom to focus on your requirements.

**Comment by cbornet** [comment]
@sta-szek would you share your `JacksonMixInAnnotations` code ? I would want to do something similar.

**Comment by sta-szek** [comment]
Hi, unfortunately I don't have access to this annotations anymore. Maybe @SemionPar can help here? 
In general basic example from https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations worked for us.
