### ISSUE TITLE
Log stacktrace for 4xx client errors (still in level WARN)

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#104]

**Comment by AlexanderYastrebov** [comment]
Could be configurable

**Comment by whiskeysierra** [comment]
What should be the default?

**Comment by whiskeysierra** [comment]
I thought about it again and I'm not sure whether one actually needs the stack trace in that case. Sure it could help in some cases here and there but on the other hand polluting the log files (also during tests) may not be worth it. Ultimately the `log` message is part of the interface and could therefore easily be overwritten, if needed. I'll close this now until someone reopens this.

**Comment by darioseidl** [comment]
I would also like it, if this was configurable with a boolean. When developing and debugging a 4xx error, it would be nice to just flip a flag and have the stack trace available. Not all 4xx errors are really client errors, sometimes they result from bugs too.

Could this be reponened? I would also be willing to work on a pull-request.

Some other thoughts: In the current implementation, only the status and the exception message is logged, but not the type of exception. That also makes it difficult to debug. And the current implementation only logs 4xx and 5xx status codes. In the rare and strange case that an exception would produce any other status code, nothing would be logged. It's unlikly, but if it happens it would be hard to spot.

What would you think about a default log implmentation that
1) unless disabled, warns about 4xx errors without stack trace, with info about exception class, status code and exception message
2) for all other errors, keeps the current behavior of logging status code and stack trace
?
