### ISSUE TITLE
Ready to use Problem exception

### ISSUE THREAD

**Issue by cbornet** [zalando/problem-spring-web#106]
It would be great to have a ready-to-use `ProblemException` runtime exception that you can throw from your controller and that will be mapped to a problem+json.

**Comment by whiskeysierra** [comment]
It doesn't fit your name suggestion (which I actually like), but it's there: [DefaultProblem](https://github.com/zalando/problem/blob/master/problem/src/main/java/org/zalando/problem/DefaultProblem.java)

**Comment by cbornet** [comment]
You're right ! I hadn't realized that it extended RuntimeException, thanks !
