### ISSUE TITLE
Support ResponseStatus annotation

### ISSUE THREAD

**Issue by cbornet** [zalando/problem-spring-web#107]
I currently use
```java
    @Override
    public ResponseEntity<Problem> handleThrowable(
        final Throwable throwable,
        final NativeWebRequest request) {
        ResponseStatus responseStatus = AnnotationUtils.findAnnotation(throwable.getClass(), ResponseStatus.class);
        if (responseStatus != null) {
            Problem problem = Problem.builder()
                .withStatus(new HttpStatusAdapter(responseStatus.value()))
                .withTitle(responseStatus.value().getReasonPhrase())
                .withDetail(responseStatus.reason())
                .build();
            return create(throwable, problem, request);
        } else {
            return create(Response.Status.INTERNAL_SERVER_ERROR, throwable, request);
        }
    }
```
to handle exceptions annotated with ResponseStatus but I think it would be nicer to have it handled directly in the lib.

**Comment by whiskeysierra** [comment]
Didn't know that Spring supports `@ResponseStatus` on exception classes. Definitely a useful extension.

**Comment by whiskeysierra** [comment]
If you take a look at Spring's implementation you can see that it falls back to the `@ResponseStatus` annotation on the cause of the exception (and tries to walk up the causal chain recursively). 

I'd try to mimic this. Any objections?

**Comment by cbornet** [comment]
No objection. What I did was enough for me but certainly not the best !
