### ISSUE TITLE
Async CompletableFuture append errors

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#114]
I'm not totally sure error comes from _problem spring web_ but if I have a controller with following code:

```java
@PutMapping(value = "/{name}")
public CompletableFuture<User> updateLaboratoryByName(@RequestBody User user) {
    return service.save(laboratory).thenApply(this::toLaboratoryResponse);
}
```

With basic service

```java
@Async
@Transactional
public CompletableFuture<user> save(User user) {
    if (<SOME CONDITION, WHATEVER>) {
        thrown new IllegalArgumentException("blabla");
    }
    return CompletableFuture.completedFuture(repository.save(laboratory));
}
```

Both messages will be display on response

```
{
	"title": "Internal Server Error",
	"status": 500,
	"detail": "java.lang.IllegalArgumentException: blabla"
}{
	"timestamp": "2017-09-25T12:16:50.615+0000",
	"status": 500,
	"error": "Internal Server Error",
	"exception": "java.util.concurrent.CompletionException",
	"message": "java.lang.IllegalArgumentException: blabla",
	"path": "/api/v1/users/XXXXX"
}
```

**Comment by whiskeysierra** [comment]
It outputs two different json objects next to each other? :open_mouth:

**Comment by kakawait** [comment]
@whiskeysierra Yes is pure raw output I posted. But maybe I'm not using the good way `CompletableFuture` I'm trying test with `DeferredResult` which include built-in `setErrorResult()` where we can pass `Exception`. I will keep you in touch

**Comment by kakawait** [comment]
@whiskeysierra I created a simple sample to reproduce issue with `/sync` working and `/async` is not. In fact if you put some `breakpoint` on `DummyControllerAdvice`, I noticed that method is not call on `async` mode.

https://github.com/kakawait/problem-spring-web-async-issue

**Comment by kakawait** [comment]
(I will stop flooding) the main difference is if I remove `implements ProblemHandling, SpringAdviceTrait` from `DummyControllerAdvice` and rewrite method like following

```java
@ExceptionHandler(IllegalArgumentException.class)
public ResponseEntity<?> handleRuntimeException(NativeWebRequest req, IllegalArgumentException e) {
	return ResponseEntity.badRequest().body("ERROR");
}
```

Even in `async` mode method is called contrary when using _problem spring web_

**Comment by kakawait** [comment]
In fact the issue comes from https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/general/ThrowableAdviceTrait.java#L16 that catches every `Throwable` including `CompletionException`

If I use following code is working 

```java
@ControllerAdvice
static class DummyControllerAdvice implements SpringAdviceTrait {

	@ExceptionHandler(IllegalArgumentException.class)
	public ResponseEntity<?> handleIllegalArgumentException(NativeWebRequest req, IllegalArgumentException e) {
		if (req.getParameter("string") != null) {
			return ResponseEntity.badRequest().body("ERROR");
		} else {
			return create(HttpStatus.BAD_REQUEST, e, req);
		}
	}
}
```

Note that `implements ProblemHandling` has been removed.

I don't find (for the moment) how to say _for that type of Exception do nothing_.

Other solution will be to convert `CompletableFuture` to `DeferredResult` like following http://lukaszkusnierz.org/blog/completablefuture-to-deferredresult/ that **unwrap** `Exception` inside `CompletionException`

**Comment by whiskeysierra** [comment]
The second response comes from spring. Only the first is an actual problem. Not sure why, yet.

**Comment by kakawait** [comment]
@whiskeysierra I just saw is not directly linked to `CompletionException` because since I'm moving to **unwrap** `CompletionException` with `DeferredResult` (see previous comment) I still have the same issue when any `Exception` encapsulate other `Exception` like following error (but I'm still using _async_)

```
{
	"title": "Internal Server Error",
	"status": 500,
	"detail": "org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance beforeQuery flushing: com.ds.design.domain.expertise.Expertise; nested exception is java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance beforeQuery flushing: com.ds.design.domain.expertise.Expertise"
}{
	"timestamp": "2017-09-26T08:36:00.708+0000",
	"status": 500,
	"error": "Internal Server Error",
	"exception": "org.springframework.dao.InvalidDataAccessApiUsageException",
	"message": "org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance beforeQuery flushing: com.ds.design.domain.expertise.Expertise; nested exception is java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance beforeQuery flushing: com.ds.design.domain.expertise.Expertise",
	"path": "/api/v0/users/XXXXXX"
}
```

I will try the same _error_ without _async_ and update comment

**Comment by kakawait** [comment]
@whiskeysierra I did some tests to limit scope:

### Buggy

```java
@ControllerAdvice
public class ExceptionHandlerControllerAdvice implements SpringAdviceTrait {

    @ExceptionHandler
    public ResponseEntity<Problem> handleThrowable(Throwable throwable, NativeWebRequest request) {
        return create(throwable, request);
    }
}
```

### Buggy

@ControllerAdvice
public class ExceptionHandlerControllerAdvice implements SpringAdviceTrait {

    @ExceptionHandler
    public ResponseEntity<Problem> handleThrowable(Throwable throwable, NativeWebRequest request) {
        return ResponseEntity.badRequest().body(create(throwable, request).getBody());
    }
}

### Works great

```java
@ControllerAdvice
public class ExceptionHandlerControllerAdvice implements SpringAdviceTrait {

    @ExceptionHandler
    public ResponseEntity<String> handleThrowable(Throwable throwable, NativeWebRequest request) {
        return ResponseEntity.badRequest().body("ok");
    }
}
```

### Works great

```java
@ControllerAdvice
public class ExceptionHandlerControllerAdvice implements SpringAdviceTrait {

    @ExceptionHandler
    public ResponseEntity<ErrorMessage> handleThrowable(Throwable throwable, NativeWebRequest request) {
        return ResponseEntity.badRequest().body(new ErrorMessage("test", "details"));
    }
    
    public static class ErrorMessage {
        private String message;
        
        private String details;

        public ErrorMessage(String message, String details) {
            this.message = message;
            this.details = details;
        }
    }
}
```

---

It seems something related to `Problem` returns type

**Comment by kakawait** [comment]
I found that append error comes from https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/error/BasicErrorController.java#L100 but I don't know why Spring internally forward to that handler...

**Comment by whiskeysierra** [comment]
We always exclude that one from our applications:

```java
@EnableAutoConfiguration(exclude = ErrorMvcAutoConfiguration.class)
```

@lukasniemeier-zalando Can you remember why exactly?

**Comment by kakawait** [comment]
@whiskeysierra Effectively that exclusion fix the issue.

**Comment by whiskeysierra** [comment]
@kakawait I created #119 to enhance the readme. I'm not sure how to fix this programatically.

**Comment by kakawait** [comment]
@whiskeysierra yes no prob, doc is enough. Thank you
