### ISSUE TITLE
Support Spring 5 and Spring Boot 2

### ISSUE THREAD

**Issue by rohit-zabbed** [zalando/problem-spring-web#121]
Looking forward to support of springboot2, atleast with spring web-mvc

**Comment by whiskeysierra** [comment]
I haven't looked at it yet. Can you highlight some incompatibilities for me?

**Comment by sbraconnier** [comment]
I use Spring Boot 2.0.0.M7 and so far so good.

The only thing I did that is not specified in the documentation is the way an ObjectMapper is configured. I didn't want to loose the Jackson auto configuration feature, so the required modules are registered like this:

```java
@Bean
public Jackson2ObjectMapperBuilderCustomizer jacksonCustomizer() {

  return builder -> {

    // We must register problem-spring-web modules. See:
    // https://github.com/zalando/problem-spring-web#configuration
    builder.modules(new ProblemModule(), new ConstraintViolationProblemModule());
  };
}
```

**Comment by rohit-zabbed** [comment]
Thats really helpful, unfortunately didn't explored lot on boot 2 since we
finally stuck with 1.5.9.

**Comment by jackstevenson** [comment]
Just came across this library and wanted to point out another way of registering the Problem modules while retaining the Jackson auto-config.

From the [Spring Boot Reference](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-the-jackson-objectmapper):

> Any beans of type com.fasterxml.jackson.databind.Module are automatically registered with the auto-configured Jackson2ObjectMapperBuilder and are applied to any ObjectMapper instances that it creates.

e.g.
```java
@Configuration
public class JacksonConfig {

    @Bean
    public ProblemModule problemModule() {
        return new ProblemModule();
    }

    @Bean
    public ConstraintViolationProblemModule constraintViolationProblemModule() {
        return new ConstraintViolationProblemModule();
    }
}
```

**Comment by cbornet** [comment]
The lib works great on JHipster 5 with Spring Boot 2 (mvn). I don’t think there’s anything to do there.

**Comment by whiskeysierra** [comment]
> The lib works great on JHipster 5 with Spring Boot 2 (mvc). I don’t think there’s anything to do there.

Except this, I guess (quoting you):

> BTW the dependency should maybe be set as provided to prevent overriding the one set by the user.
>
> https://github.com/zalando/problem-spring-web/issues/137#issuecomment-388767682
