### ISSUE TITLE
Throwing and catching Problem exceptions in Jhipster's microservices.

### ISSUE THREAD

**Issue by javasparx** [zalando/problem-spring-web#128]
I use problem-spring-web in my every spring project but I couldn't use it to customize OAuth2 exceptions.
It would be perfect if you provide sample project. Thank you in advance.

**Comment by eloo** [comment]
i guess you have configured the exceptionhandling using the configure method of a resourceserverconfigadaper?

maybe you can try to set the accessDeniedHandler and authenticationEntryPoint of the resource too like this
`    @Override
    public void configure(ResourceServerSecurityConfigurer resources) {
        resources.accessDeniedHandler(problemSupport).authenticationEntryPoint(problemSupport);
    }`

I'm not sure if this is a proper way but in my case it works

**Comment by javasparx** [comment]
I can see cool code examples in the main page, but I couldn't use them in real microservice. As I said before, it will be more useful to see real example.

**Comment by whiskeysierra** [comment]
@javasparx What's the behaviour that you observe? What isn't working?

**Comment by javasparx** [comment]
I am using Jhipster microservices. I have microservice UAA with OAauth2. I extended DaoAuthProvide from Spring Security and added some Two Factor Auth logic. In the logic I want to throw exceptions like : ENTRY_CODE_LIMIT_EXCEEDED, WRONG_CODE_TRY_AGAIN and etc. using my 'Problem' exceptions.
Login procedure goes throw Gateway microservice and my exceptions from UAA catched as Spring Security Auth exceptions but not Problem exceptions in the Gateway.

**Comment by whiskeysierra** [comment]
I'm assuming you're running a setup like [this](https://www.jhipster.tech/using-uaa/), correct? Where exactly is your problem located? In the Gateway? Sounds like your gateway is not deserializing your problem correctly. That would be out of scope of this project, but rather part of https://github.com/zalando/problem directly.

**Comment by javasparx** [comment]
You are right, @whiskeysierra. Could you suggest how to produce "AbstractThrowableProblem" instead of "Security Exception" like BadCredentialsException and etc.? I could manage it from wiki.

**Comment by whiskeysierra** [comment]
How do you deserialize your exceptions?

**Comment by javasparx** [comment]
OK, I solve my problem:
1. TokenEndpoint catches all exceptions with @ExceptionHandler In UAA microservice. I replaced it with my custom class to let ExceptionTranslator throw Problems.
2.  I changed default loadBalancedRestTemplate in Gateway microservice. Otherwise, exception's body was empty string.
```
    @Bean
    @Qualifier("loadBalancedRestTemplate")
    public RestTemplate loadBalancedRestTemplate(RestTemplateCustomizer customizer) {
        RestTemplate restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory());
        customizer.customize(restTemplate);
        return restTemplate;
    }
```

**Comment by cbornet** [comment]
@javasparx if you have improvements to the code generated by JHipster, don't hesitate to contribute them to the project !

**Comment by amirensit** [comment]
@javasparx Can you please provide some code how to add  the custom `TokenEndPoint` in the uaa microservice ?
