### ISSUE TITLE
Mention specialties in controller advices

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#13]
@lukasniemeier-zalando Which exceptions are only passed to @ExceptionHandler method if the @ControllerAdvice does not list specific controller classes, but advises all of them?

I think we should mention that in the readme and in the corresponding advice trait's javadocs.

**Comment by lukasniemeier-zalando** [comment]
It's at least ``NoHandlerFoundAdviceTrait ``
