### ISSUE TITLE
Support Spring Webflux applications

### ISSUE THREAD

**Issue by cbornet** [zalando/problem-spring-web#137]
It would be great so we can use problem-spring-web with fully reactive applications.
Currently the lib depends on spring-webmvc which can't be used along with spring-webflux.

**Comment by whiskeysierra** [comment]
I haven't used WebFlux myself yet. How does Spring 5 deal with exception handling on the web layer?

**Comment by cbornet** [comment]
`@ControllerAdvice` should still work but I don't know the details. The biggest challenge I think is to remove all usage of javax.servlet.* and org.springframework.web.servlet.* of the library. Or if it's not possible for some of the classes, having a way to exclude them from component scanning (eg. SecurityProblemSupport) and putting spring-mvc dep as provided.

**Comment by cbornet** [comment]
I had a deeper look and ExceptionHandler/ControllerAdvice do work on Webflux. The difficulty is that the lib relies on servlet’s NativeWebRequest to do content negotiation and for a hack on 406 errors. The equivalent of NativeWebRequest in Webflux is ServerWebExchange. HttpEntity could be used as a common method argument to get the accept headers but it will not work for the 406 hack. So the possibilities are : find another way to handle the 406 error than the hack, or write new traits for Webflux, maybe in another lib. WDYT ?

**Comment by cbornet** [comment]
Since #124 there is now always a body in fallback. So is the hack still needed ?

**Comment by whiskeysierra** [comment]
> Since #124 there is now always a body in fallback.

There is a body by default, but users of the library might choose to override `fallback` and switch back to the old behavior.

> So is the hack still needed?

If we decide that a fallback without body is unsupported, then no. But I'm not sure whether it's safe to do that.

**Comment by cbornet** [comment]
The webmvc artifact will pull Spring 4 but the Webflux one will need to pull Spring 5.

**Comment by cbornet** [comment]
BTW the dependency should maybe be set as provided to prevent overriding the one set by the user.
