### ISSUE TITLE
Error 500 returns text/html in Spring Boot 2 & Tomcat

### ISSUE THREAD

**Issue by omegas27** [zalando/problem-spring-web#171]
Error 500 returns text/html response type in Spring Boot 2 & Tomcat
 
## Description
Error 500, even if they are handled by a trait (ThrowableAdviceTrait) are transformed in Spring Boot 2 with Tomcat in an text/html response.

In the AdviceTrait class, this line causes the issue :
if (status == HttpStatus.INTERNAL_SERVER_ERROR) {
    request.setAttribute(ERROR_EXCEPTION, throwable, SCOPE_REQUEST);
}

**Comment by whiskeysierra** [comment]
Are you using an embedded tomcat or standalone?

**Comment by omegas27** [comment]
I'm using Spring Boot embedded server

**Comment by whiskeysierra** [comment]
Did you disable the `ErrorMvcAutoConfiguration`?

```java
@EnableAutoConfiguration(exclude = ErrorMvcAutoConfiguration.class)
```

**Comment by omegas27** [comment]
I used @SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class). Switching to @EnableAutoConfiguration(exclude = ErrorMvcAutoConfiguration.class) changes nothing. It works for every kind of error message apart from Internal Server Error because of the line i sent in the issue

**Comment by whiskeysierra** [comment]
@omegas27 Could you provide either a test case or a sample project to highlight the issue?

**Comment by whiskeysierra** [comment]
I can't reproduce it.

```http
HTTP/1.1 500 
Connection: close
Content-Type: application/problem+json
Date: Thu, 31 May 2018 20:40:25 GMT
Transfer-Encoding: chunked
X-Flow-ID: RwpIfe3q98Tn6NfceoezmA

{
    "detail": "Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.",
    "status": 500,
    "title": "Internal Server Error"
}
```

**Comment by omegas27** [comment]
I tried a clean set up and it works as expected. It's probably a misconfiguration in my project. I'll try to find what makes it not work as expected

**Comment by alobaton** [comment]
Hi @omegas27, 

I'm having the same problem. If you managed to find a solution, could you share it? 

Thanks.

**Comment by leosudeep1** [comment]
@alobaton probably you are using @JsonProperty, which have duplicate key in response.

**Comment by darioseidl** [comment]
Another reason can be a missing configuration of `SecurityProblemSupport` (which implements `AuthenticationEntryPoint` and `AccessDeniedHandler`). See https://github.com/zalando/problem-spring-web/blob/main/problem-spring-web/README.md#security

```
@Configuration
@Import(SecurityProblemSupport.class)
public class SecurityConfiguration extends ResourceServerConfigurerAdapter {

    @Autowired
    private SecurityProblemSupport problemSupport;

    @Override
    public void configure(final HttpSecurity http) {
        http.exceptionHandling()
                .authenticationEntryPoint(problemSupport)
                .accessDeniedHandler(problemSupport);
    }

}
```
