### ISSUE TITLE
Make Spring 5/Spring Boot 2 the default

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#183]
## Detailed Description

This library is compiled, build and released against Spring 4 and Spring Boot 1 by default. Support for Spring 5 and Spring Boot 2 is supported via special build profiles that are primarily used by travis.

The goal is to change the default to Spring 5 and Spring Boot 2.

## Context

In the upcoming weeks, we're trying to move to Spring Boot 2 internally. It's therefore the next logical step to have all libraries support it natively.

## Possible Implementation

- change spring versions in `properties` section
- rename `spring5` profile to `spring4`
- merge any `spring4-*` profiles into `spring4`
- introduce `webflux` profile
  - active by default
  - adds `problem-spring-webflux` module
  - can (should) be manually disabled when building against spring 4, e.g. `mvn clean verify -P spring4,-webflux`
- remove any profile from `release.sh` except `release`

**Comment by cbornet** [comment]
@whiskeysierra can we expect a release soon 😃 ?

**Comment by whiskeysierra** [comment]
On it.

**Comment by whiskeysierra** [comment]
@cbornet https://github.com/zalando/problem-spring-web/releases/tag/0.24.0-RC.0
