### ISSUE TITLE
Add support for ResponseStatusException

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#188]
## Detailed Description

The web module doesn't support it out of the box.

## Your Environment

* Version used:
* Link to your project:

**Comment by cbornet** [comment]
Maybe that could go in a dedicated sub-module ?

**Comment by whiskeysierra** [comment]
Not sure if that's worth the effort.

**Comment by cbornet** [comment]
Indeed 😄

**Comment by cbornet** [comment]
Maybe a recipe in the README
