### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#191]
## Description

See #180.

## Expected Behavior

Migration to multi-module should've been backwards compatible.

## Actual Behavior

Some classes were accidentally moved to a different package.

## Possible Fix

Move classes back.

## Your Environment

* Version used: 0.24.0-RC.0

**Comment by whiskeysierra** [comment]
https://diff.revapi.org/?groupId=org.zalando&artifactId=problem-spring-web&old=0.23.0&new=0.24.0-RC.0

**Comment by whiskeysierra** [comment]
@cbornet Are you willing to propose a PR?

**Comment by cbornet** [comment]
Yes I can work on that.

**Comment by cbornet** [comment]
I don't forget this, but I have so much on my plate right now...

**Comment by whiskeysierra** [comment]
I'd actually be fine with just double checking that the package names are good now (and not overlapping between different jars/artifacts) and then we go with a breaking change. We are still in 0.x territory, so nothing prevents us from doing so.

**Comment by cbornet** [comment]
@whiskeysierra do you see issues with package names ? I'll try to find time to work on this now if needed.

**Comment by whiskeysierra** [comment]
Names are fine, I believe.
