### ISSUE TITLE
Aggregate Advice Traits

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#2]
Might be useful to aggreate some/all/any of the traits into pre-compiled ones.

**Comment by whiskeysierra** [comment]
I'd suggest we have at least a big one for *all* traits, e.g. `ProblemHandling`.

Groups of traits would be nice as well, I'm just not sure how to split them in to meaningful subsets. Maybe

- http
  - method not allowed
  - unsupported media type
  - not acceptable
- routing
  - no handler
  - no such request handler method
  - missing servlet request parameter
  - missing servlet request part
- io
  - message not readable
  - multipart
- validation
  - method argument not valid
  - constraint violation
- custom
  - not found (`NotFoundAdviceTrait<N extends Exception>`)
- general
  - problem
  - throwable

**Comment by whiskeysierra** [comment]
I did a splitup into groups and composite advice traits in pr #4

**Comment by lukasniemeier-zalando** [comment]
Fixed in #4
