### ISSUE TITLE
Not works for exceptions from spring security Oauth2 with JWT.

### ISSUE THREAD

**Issue by ferinoc** [zalando/problem-spring-web#233]
I'm not able to setup "problems" for exceptions thrown by spring security Oauth2 with JWT.

step to reproduce:
1) setup project from this tutorial: https://www.youtube.com/watch?v=wxebTn_a930 
There is github link to clone project or I attached my try out. 
[spring-boot2-oauth2-auth-server-jwt-zalando.zip](https://github.com/zalando/problem-spring-web/files/2530956/spring-boot2-oauth2-auth-server-jwt-zalando.zip)
[sql.txt](https://github.com/zalando/problem-spring-web/files/2531061/sql.txt)

2) setup zalando problems from https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web -> Security

3) do post request on /oauth/token with wrong credetials e.g admin/password2

4) response looks like:
{
    "error": "unauthorized",
    "error_description": "Bad credentials"
}

Note: Attached project is just example. If you could provide any working example with spring boot 2+, Oauth2 and JWT would be great. Thank you very much.

**Comment by whiskeysierra** [comment]
https://github.com/zalando/problem-spring-web/blob/master/problem-spring-web/README.md#security

Did you follow that step?

**Comment by ferinoc** [comment]
yes, I think I did all steps. On another project where spring security is used (but not with Oauth2), zalando problem works fine for me.

**Comment by whiskeysierra** [comment]
I'm on mobile right now and was hoping that it's something simple. I'll take a look as soon as I can.

**Comment by whiskeysierra** [comment]
I took a look but I can't easily run it myself (too lazy to set up the database/schema/etc.). I don't believe we use the oauth2 extensions in spring security therefore I'm not 100% sure, but I could imagine that setting the access denied handler and authentication entry point here could fix your issue:

```java
	@Override
	public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
		oauthServer.tokenKeyAccess("permitAll()").checkTokenAccess("isAuthenticated()");
	}
```

**Comment by ferinoc** [comment]
thank you for replay, I tried that already but didn't help me. Tomorrow I will try prepare example with H2 database to have better example. 
I found that OAuth2AuthenticationEntryPoint is created on more places so may be setup entry point on more places is needed.
![image](https://user-images.githubusercontent.com/1408155/47751818-11b24880-dc93-11e8-8ea1-c3ea36b470fa.png)

I found also some discussion but didn't try them yet (I would prefer setup entry point) e.g.:
https://github.com/spring-projects/spring-security-oauth/issues/610

**Comment by ferinoc** [comment]
I created new spring boot project (with oauht2 and zalando problems) which should be simpler. It should be possible run without any configuration.
Can be download here: https://bitbucket.org/ferinoc/zalando-web-oauth2.git

There is class IntegrationTest which contains "tests":
provideTokenCorrectCredentials - jwt token should be generated successfully to console
provideTokenWrongUserName - throw exception, but exception is not catch in GeneralExceptionHandler

If you could check and try to make zalando problem works would be great :) Thank you.

**Comment by whiskeysierra** [comment]
Looks like the `TokenEndpoint` implements a local `@ExceptionHandler` method that takes precedence. Looking into `ExceptionHandlerExceptionResolver`:

```
	@Nullable
	protected ServletInvocableHandlerMethod getExceptionHandlerMethod(
			@Nullable HandlerMethod handlerMethod, Exception exception) {

		Class<?> handlerType = null;

		if (handlerMethod != null) {
			// Local exception handler methods on the controller class itself.
			// To be invoked through the proxy, even in case of an interface-based proxy.
			handlerType = handlerMethod.getBeanType();
			ExceptionHandlerMethodResolver resolver = this.exceptionHandlerCache.get(handlerType);
			if (resolver == null) {
				resolver = new ExceptionHandlerMethodResolver(handlerType);
				this.exceptionHandlerCache.put(handlerType, resolver);
			}
			Method method = resolver.resolveMethod(exception);
			if (method != null) {
				return new ServletInvocableHandlerMethod(handlerMethod.getBean(), method);
			}
			// For advice applicability check below (involving base packages, assignable types
			// and annotation presence), use target class instead of interface-based proxy.
			if (Proxy.isProxyClass(handlerType)) {
				handlerType = AopUtils.getTargetClass(handlerMethod.getBean());
			}
		}

		for (Map.Entry<ControllerAdviceBean, ExceptionHandlerMethodResolver> entry : this.exceptionHandlerAdviceCache.entrySet()) {
			ControllerAdviceBean advice = entry.getKey();
			if (advice.isApplicableToBeanType(handlerType)) {
				ExceptionHandlerMethodResolver resolver = entry.getValue();
				Method method = resolver.resolveMethod(exception);
				if (method != null) {
					return new ServletInvocableHandlerMethod(advice.resolveBean(), method);
				}
			}
		}

		return null;
	}
```

> Local exception handler methods on the controller class itself.

and then later it inspects controller advices.

**Comment by ferinoc** [comment]
hmm
I'm looking on org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration. 
In method "configure" there is: 
ResourceServerSecurityConfigurer resources = new ResourceServerSecurityConfigurer();
where entry point is set:  
AuthenticationEntryPoint authenticationEntryPoint = new OAuth2AuthenticationEntryPoint();

I'm thinking if is possible somehow overwrite it.

Strange for me is that in my ResourceServerConfig in method:
configure(HttpSecurity httpSecurity) the different instance of HttpSecurity is passed that in spring ResourceServerConfiguration

**Comment by whiskeysierra** [comment]
I can't really help you much. We don't run an auth server within the same service, for us it's a centrally provided endpoint.

**Comment by ferinoc** [comment]
could you please provide more info how you are doing auth?
I'm thinking about the "best practices" to protect "Rest API application"
which provide api for more applications.
In one project we have "simple controller" which provide us JWT token. But
I'm not sure if that is way to go for "API application". I read that Oauht2
protocol with JWT token should be used. Many thanks

**Comment by whiskeysierra** [comment]
http://docs.stups.io/en/latest/user-guide/access-control.html

**Comment by ferinoc** [comment]
I overwrite /oauth/token endpoint with custom controller. Now zalando problem is working. Could you please take a look if that could be solution or do you think is not good practise? Thank you.

Git: https://bitbucket.org/ferinoc/zalando-web-oauth2
Clone link: https://bitbucket.org/ferinoc/zalando-web-oauth2.git

**Comment by whiskeysierra** [comment]
@ferinoc Did you solve this?

**Comment by ferinoc** [comment]
I created controller for /oauth/token which wrapped most of Oauht2 exceptions:
(at the moment is enough for my project, later may be will look again on it)

`@RestController
public class Oauth2Controller {

    private final TokenEndpoint tokenEndpoint;

    public Oauth2Controller(TokenEndpoint tokenEndpoint) {
        this.tokenEndpoint = tokenEndpoint;
    }

    @PostMapping(value = "/oauth/token")
    public ResponseEntity<OAuth2AccessToken> postAccessToken(Principal principal, @RequestParam Map<String, String> parameters)
            throws HttpRequestMethodNotSupportedException {
        return tokenEndpoint.postAccessToken(principal, parameters);
    }

}`

**Comment by whiskeysierra** [comment]
Does the OAuth spec actually allow custom error responses?

**Comment by amirensit** [comment]
It allows it using DefaultWebResponseTranslator which is used by default in TokenEndpoint class.
In jhipster uaa microservice, I think that there is too much work to add to get oauth2 Spring security exception using Zalando.
Anyway, I aborded this solution since It took more than 2 weeks without result.

**Comment by whiskeysierra** [comment]
> It allows it using DefaultWebResponseTranslator which is used by default in TokenEndpoint class.
> In jhipster uaa microservice,

I'm not asking about whether it's possible given the implementation, but whether the OAuth 2 spec/standard actually allows custmomized error responses. I don't believe it's allowed, therefore there is no issue here, imho:

https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/#error
