### ISSUE TITLE
Don't work without SpringSecurity dependency

### ISSUE THREAD

**Issue by eustimenko** [zalando/problem-spring-web#235]
## Description

There are Spring Security components at org.zalando.problem.spring.web.advice.security.SecurityProblemSupport

That reason to have additional spring security dependency in the project.
## Expected Behavior

I'd like be able to exclude artifact with spring security component.

## Actual Behavior

I should include additional spring security dependency into my project and configure to ignore that.
## Possible Fix

Move classes with Spring Security libraries to separate component.
## Steps to Reproduce

1. Create spring-boot project without spring security
2. Add zalango/problem-spring-web
3. Configure tool using README manual
4. Launch the project
5. You will see the message 
java.lang.ClassNotFoundException: org.springframework.security.core.AuthenticationException

## Context

I should add and configure SpringSecurity in my project.
## Your Environment

* Version used: 0.24.0-RC.0
* Link to your project: under NDA

**Comment by whiskeysierra** [comment]
`ProblemHandling` extends `SecurityAdviceTrait`, but it really shouldn't:

https://github.com/zalando/problem-spring-web/blob/3f69a8b2652d997179299f8aaf71b062e5bc14f9/problem-spring-web/src/main/java/org/zalando/problem/spring/web/advice/ProblemHandling.java#L33-L38

**Comment by whiskeysierra** [comment]
> SecurityProblemSupport

This isn't the issue, since you're not using it.

**Comment by whiskeysierra** [comment]
Possible workaround for now: Instead of implementing `ProblemHandling`, extend all wanted traits yourself (i.e. everything except `SecurityAdviceTrait`)

**Comment by ivanskodje** [comment]
@whiskeysierra Excellent tip for circumventing this problem. :+1: 

```
public interface ZalandoProblemHandling extends GeneralAdviceTrait, HttpAdviceTrait, IOAdviceTrait, RoutingAdviceTrait, ValidationAdviceTrait {
}
```

That being said, is anything being done to resolve this; or are users currently expected to include security dependencies themselves to avoid the NoClassFound error? 

Cheers

**Comment by whiskeysierra** [comment]
Pull requests are highly appreciated.

**Comment by thomasabraham** [comment]
Got stuck on this for a while, found this issue when I tried to create a new one. 
Would be a good idea to document this in README.

**Comment by whiskeysierra** [comment]
What is missing from your perspective?

**Comment by thomasabraham** [comment]
I created a [PR](https://github.com/zalando/problem-spring-web/pull/324); please take a look.
