### ISSUE TITLE
Stacktrace in response

### ISSUE THREAD

**Issue by AbyssOfDeath** [zalando/problem-spring-web#238]
I have been trying to configure implement ProblemHanding but the stacktrace keep showing up in response , I tried every config , Below are pieces of code that I added to test 

```
@Bean
    fun objectMapper(): ObjectMapper {
        return ObjectMapper().registerModule(problemModule().withStackTraces(false),constraintViolationProblemModule())
    }
    @Bean
    fun problemModule(): ProblemModule {
        return ProblemModule()
    }

    @Bean
    fun constraintViolationProblemModule(): ConstraintViolationProblemModule {
        return ConstraintViolationProblemModule()
    }
```
also tried this 
 ```
@Bean
    fun problemObjectMapperModules(): Jackson2ObjectMapperBuilderCustomizer {
        return Jackson2ObjectMapperBuilderCustomizer { jacksonObjectMapperBuilder ->
            jacksonObjectMapperBuilder.modules(problemModule().withStackTraces(false), constraintViolationProblemModule())
        }

    }
```

Also my implementation for ProblemHandling 
```

@RestControllerAdvice
class ExceptionTranslator : ProblemHandling {
    override fun isCausalChainsEnabled(): Boolean {
        return false
    }
    /**
     * Post-process Problem payload to add the message key for front-end if needed
     */
    override fun process(entity: ResponseEntity<Problem>, request: NativeWebRequest): ResponseEntity<Problem>? {
        if (entity.body == null) {
            return entity
        }
        val problem = entity.body
        if (!(problem is ConstraintViolationProblem || problem is DefaultProblem)) {
            return entity
        }
        val builder = Problem.builder()
                .withType(if (Problem.DEFAULT_TYPE == problem.type) ErrorConstants.DEFAULT_TYPE else problem.type)
                .withStatus(problem.status)
                .withTitle(problem.title)
                .with("path", request.getNativeRequest(HttpServletRequest::class.java)!!.requestURI)

        if (problem is ConstraintViolationProblem) {
            builder
                    .with("violations", problem.violations)
                    .with("message", ErrorConstants.ERR_VALIDATION)
            return ResponseEntity(builder.build(), entity.headers, entity.statusCode)
        } else {
            builder
                    //.withCause((problem as DefaultProblem).cause)
                    //.withDetail(problem.detail)
                    .withInstance(problem.instance)
            problem.parameters.forEach { key, value -> builder.with(key, value) }
            if (!problem.parameters.containsKey("message") && problem.status != null) {
                builder.with("message", "error.http." + problem.status!!.statusCode)
            }
            return ResponseEntity(builder.build(), entity.headers, entity.statusCode)
        }

    }

    override fun handleMethodArgumentNotValid(ex: MethodArgumentNotValidException, request: NativeWebRequest): ResponseEntity<Problem> {
        val result = ex.bindingResult
        val fieldErrors = result.fieldErrors.stream()
                .map { f -> FieldErrorVM(f.objectName, f.field, f.code!!) }
                .collect(Collectors.toList())

        val problem = Problem.builder()
                .withType(ErrorConstants.CONSTRAINT_VIOLATION_TYPE)
                .withTitle("Method argument not valid")
                .withStatus(defaultConstraintViolationStatus())
                .with("message", ErrorConstants.ERR_VALIDATION)
                .with("fieldErrors", fieldErrors)
                .build()
        return create(problem, request)
    }

    @ExceptionHandler(NoSuchElementException::class)
    fun handleNoSuchElementException(ex: NoSuchElementException, request: NativeWebRequest): ResponseEntity<Problem> {
        val problem = Problem.builder()
                .withStatus(Status.NOT_FOUND)
                .with("message", ErrorConstants.ENTITY_NOT_FOUND_TYPE)
                .build()
        return create(problem, request)
    }

    @ExceptionHandler(NullPointerException::class)
    fun handleNullPointerException(ex: NullPointerException, request: NativeWebRequest): ResponseEntity<Problem> {
        val problem = Problem.builder()
                .withStatus(Status.NOT_FOUND)
                .with("message", ErrorConstants.ENTITY_NOT_FOUND_TYPE)
                .build()
        ex.stackTrace
        return create(problem, request)
    }


    @ExceptionHandler(BadRequestAlertException::class)
    fun handleBadRequestAlertException(ex: BadRequestAlertException, request: NativeWebRequest): ResponseEntity<Problem> {
        return create(ex, request, HeaderUtil.createFailureAlert(ex.entityName, ex.errorKey, ex.message))
    }

    @ExceptionHandler(ConcurrencyFailureException::class)
    fun handleConcurrencyFailure(ex: ConcurrencyFailureException, request: NativeWebRequest): ResponseEntity<Problem> {
        val problem = Problem.builder()
                .withStatus(Status.CONFLICT)
                .with("message", ErrorConstants.ERR_CONCURRENCY_FAILURE)
                .build()
        return create(ex, problem, request)
    }
}
```

I have `server.error.include-stacktrace=never` in property files
 this is my response https://gist.github.com/AbyssOfDeath/548727d9bb655bf993aaec762e44e57a

**Comment by whiskeysierra** [comment]
Your response is an indicator that your object mapper is not being used (that's the default behaviour without our modules. Get rid of the object mapper (Spring Boot 2) or rename it to `jacksonObjectMapper` (Spring Boot 1).

**Comment by AbyssOfDeath** [comment]
@whiskeysierra  Tried that one as well but same thing

**Comment by AbyssOfDeath** [comment]
https://gist.github.com/AbyssOfDeath/865e4764982eea7d4037d05d2c5376dc <-- this response afterwards

**Comment by whiskeysierra** [comment]
Your problem is not limited to problem spring web. You can try to modify any configuration on the object mapper to prove that it's not actually being used. If you fix your set up in that regard that you modifications to the object mapper apply, then you problem-spring-web will work.

**Comment by postace** [comment]
@whiskeysierra  I see that your README.md is inaccurate about stack trace.
This line below is not true
> 
In case you want to enable stack traces, please configure your ProblemModule as follows:
...
>

**Comment by onlyshow** [comment]
me too, default enable stack traces
version:0.23.0

**Comment by onlyshow** [comment]
在configureMessageConverters冲突了

**Comment by whiskeysierra** [comment]
Can you show me a sample configuration and response? @postace @onlyshow

**Comment by cbornet** [comment]
Best would be a sample github project with your issue that can be cloned.

**Comment by onlyshow** [comment]
`@Configuration
@EnableWebMvc
@ComponentScan(basePackages = {"com.ejar.controller"})
public class WebConfiguration implements WebMvcConfigurer {

    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        ObjectMapper mapper = Jackson2ObjectMapperBuilder.json()
            .modules(new ProblemModule(), new ConstraintViolationProblemModule()).build();

        converters.add(new MappingJackson2HttpMessageConverter(mapper));
    }
}`

Problem solving

**Comment by whiskeysierra** [comment]
For Spring Boot 2, this is already covered in the README: https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web#configuration

**Comment by kalexmills** [comment]
@whiskeysierra, I'm not sure that you have understood some of the concerns that folks have raised here.

As of release 0.22.0 (downloaded from central) the documentation concerning configuration is misleading. The section of [this README](https://github.com/zalando/problem-spring-web/blob/master/README.md) reading

```
In case you want to enable stack traces, please configure your ProblemModule as follows:

ObjectMapper mapper = new ObjectMapper()
    .registerModule(new ProblemModule().withStackTraces());
```

suggests that stack traces are **not** enabled by default, when, in my experience, they **are**. Here is the configuration which I had to use in order to get rid of the stack traces.

```
/**
 * ZalandoConfig provides configuration for org.zalando:problem-spring-web
 */
@Configuration
public class ZalandoConfig {

  @Bean
  public Jackson2ObjectMapperBuilderCustomizer addCustomBigDecimalDeserialization() {
    return (Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder)  ->
        jacksonObjectMapperBuilder.modules(new ProblemModule().withStackTraces(false));
    }
}
```

Hope this helps.

**Comment by kalexmills** [comment]
@WhiskeySierra

> ... i.e. n stack traces.

Did you mean to say "no stack traces"? Sorry to ask.

**Comment by YingjiangLiu** [comment]
> ```
> @Configuration
> @EnableWebMvc
> @ComponentScan(basePackages = {"com.xxx.controller"})
> public class WebConfiguration implements WebMvcConfigurer {
> 
>     public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
>         ObjectMapper mapper = Jackson2ObjectMapperBuilder.json()
>             .modules(new ProblemModule(), new ConstraintViolationProblemModule()).build();
> 
>         converters.add(new MappingJackson2HttpMessageConverter(mapper));
>     }
> }
> ```
> 
> Problem solving

解决了,兄弟

**Comment by valentinacupac** [comment]
@whiskeysierra I was reading the link you mentioned for Spring Boot 2 https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web#configuration

So here's the code I added:

`
@Configuration
public class ProblemConfiguration {
    @Bean
    public ProblemModule problemModule() {
        return new ProblemModule().withStackTraces(false);
    }

    @Bean
    public ConstraintViolationProblemModule constraintViolationProblemModule() {
        return new ConstraintViolationProblemModule();
    }
}
`

When I ran the above, I get stack traces...

Thanks,
Valentina

P.S. Could you clarify the meaning of "If not using the starter module" (it appears in https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web#configuration) - what's the starter module referring to, maybe I'm missing something there.
