### ISSUE TITLE
No qualifying bean of type 'org.springframework.web.servlet.HandlerExceptionResolver' available: expected at least 1 bean which qualifies as autowire candidate

### ISSUE THREAD

**Issue by onlyshow** [zalando/problem-spring-web#249]
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfiguration': Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.zalando.problem.spring.web.advice.security.SecurityProblemSupport': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.web.servlet.HandlerExceptionResolver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value=handlerExceptionResolver)}`

github project [https://github.com/onlyshow/hello-api](https://github.com/onlyshow/hello-api) @whiskeysierra  @cbornet

**Comment by shexbeer** [comment]
How did you solve this?

**Comment by abadongutierrez** [comment]
same question

**Comment by hecvd** [comment]
Same problem as Rafa

**Comment by InternalErrorGit** [comment]
same question
