### ISSUE TITLE
Enhance documentation for Spring-boot & Jackson

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#26]
By simply following [`README.md`](https://github.com/zalando/problem-spring-web/blob/master/README.md) with a fresh `Spring Boot` application output will looks like (`stackTrace` was skipped)

```
{
"cause": null,
"stackTrace": [...],
"type": "http://httpstatus.es/405",
"title": "Method Not Allowed",
"status": "METHOD_NOT_ALLOWED",
"detail": {
"present": true
},
"instance": {
"present": false
},
"parameters": {},
"message": null,
"localizedMessage": null,
"suppressed": []
}
```

I know it's about `Jackson` configuration and precious information is related on https://github.com/zalando/problem. But it's not really user friendly to switch between the two projects to successfully find all documentation I need for my `Spring` project.

Moreover I know that configuration can depends on many things: using `Jackson` or not? Using `Spring boot` or not? 

But we can add some sample like following (`Spring boot` + `Jackson`)

```
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>problem-spring-web</artifactId>
    <version>${problem-spring-web.version}</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jdk8</artifactId>
    <version>${jackson-datatype-jdk8.version}</version>
</dependency> 
```

```
@Bean
public Jackson2ObjectMapperBuilder objectMapperBuilder() {
    return new Jackson2ObjectMapperBuilder().modules(new Jdk8Module(), new ProblemModule());
}
```

Will display

```
{
"type": "http://httpstatus.es/405",
"title": "Method Not Allowed",
"status": 405,
"detail": "Request method 'GET' not supported"
}
```

**Comment by whiskeysierra** [comment]
You're absolutely right, the current documentation is not at all clear on that. I'll copy the necessary parts from the problem repo and add them here.

**Comment by kakawait** [comment]
Other possible way rather than documentation is maybe create `Autoconfiguration` package "à la" Spring-boot

**Comment by whiskeysierra** [comment]
> Other possible way rather than documentation is maybe create Autoconfiguration package "à la" Spring-boot

I considered that, but I'm not so sure whether this library is the right one to provide a configured Jackson ObjectMapper to the Spring ApplicationContext. That's usually something that's configured/provided by the client application. And to my knowledge Spring doesn't offer good support for modifying that from the outside. Sames goes for a potential ControllerAdvice that we could provide. I would like clients to pick and choose by themselves. We could consider a default though.
