### ISSUE TITLE
503 Service Unavailable for open circuit breaker

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#265]
## Detailed Description

Translate Failsafe's `CircuitBreakerOpenException` into a probem response with a `503 Service Unavailable` status.

## Context

A `CircuitBreakerOpenException` that bubbles all the way up the web layer of an application can technically safely translated into a *service unavailable* response, since clients may be able to honor this.

## Possible Implementation

- [x] Optional dependency to [Failsafe 2.0](https://github.com/jhalterman/failsafe)
  - [x] Make sure it's really optional at runtime
- [x] Translate to [`503 Service Unavailable`](https://tools.ietf.org/html/rfc7231#section-6.6.4) 
- [x] No special problem type needed
- [x] Optionally, set [`Retry-After`](http://tools.ietf.org/html/rfc7231#section-7.1.3) header based on `CircuitBreaker#getDelay`

**Comment by whiskeysierra** [comment]
Should work similar to #235

**Comment by kakawait** [comment]
2 cents question why `503 Service Unavailable` rather than `504 Gateway Time-out`? (In context of _circuit breaker_ is used to call other services)?

**Comment by whiskeysierra** [comment]
> 504 Gateway Time-out

That might be a good choice for the very first time a down stream dependency doesn't respond in time. (Note to self: Add support for `SocketTimeoutException` as a new network advice trait?)

> why `503 Service Unavailable`

1. :arrow_forward: Incoming request
2. :arrow_forward: Outgoing request
3. :arrow_backward: Timeout :boom: 
4. :arrow_backward: Outgoing response: 504 Gateway Time-out
5. :arrow_forward: Incoming request
6. :arrow_forward: Circuit breaker open :boom: 
7. :arrow_backward: Outgoing response: 503 Service Unavailable

In case the circuit breaker is open we don't actually have a timeout since we didn't even tried to issue an outgoing request. Could be that the circuit breaker was opened due to some other exception.

Does that make sense?

**Comment by kakawait** [comment]
@whiskeysierra I think there is no silver bullet solution for that problem. Because yes _opened circuit_ will prevent to call the service but it prevents due to previous `timeout`. I mean `503 Service Unavailable`, in my mind, is your service that is `unavailable` but in fact you're are (or maybe partially)... 

But in other hand is true that you should not respond `504` if you even do not perform the call.

Endless :)

**Comment by whiskeysierra** [comment]
> but it prevents due to previous `timeout`

That's the most dominant type, yes. But circuit breakers can be opened for numerous other reasons, doesn't have to be timeouts.

> your service that is `unavailable` but in fact you're are (or maybe partially)

Not really. If a `CircuitBreakerOpenException` bubbles up all the way from an HTTP Client/Gateway to a Resource/Controller (vocabulary stolen from https://martinfowler.com/articles/microservice-testing/#anatomy-modules) then this service is not available, since there was no fallback of any kind which makes this particular dependency a critical one.

So my reasoning for `503 Service Unavailable` is the following:

> This service is really not available since (at least) one critical dependency is not available.

**Comment by kakawait** [comment]
I think tour def 

> This service is really not available since (at least) one critical dependency is not available.

Is better than mine.

In my use case (hypothetical) I'll stick to your idea but I may enhance/extends the error object/message/body (or even header I did not think enough) to add information about this `503` is related to tighly coupled dépendency failure (I'm not asking to do that built it, this lib is enough customisable to allow achieving that without effort, just wanted to share my point of view)

**Comment by whiskeysierra** [comment]
> but I may enhance/extends the error object/message/body (or even header I did not think enough) to add information about this `503` is related to tighly coupled dependency failure

That makes sense, sure.

> Thank you for time you took to respond/discuss about this concept, that was instructive

You're welcome :handshake:

**Comment by whiskeysierra** [comment]
https://github.com/jhalterman/failsafe/blob/master/CHANGES.md#211

Failsafe 2.1.1 adds support for retrieving the delay configuration: https://github.com/jhalterman/failsafe/blob/master/CHANGES.md#211
