### ISSUE TITLE
Render StackTrace if configured (not default behavior)

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#27]
I would to know if it's possible to render `stackTrace` on `JSON` error output. But with something configurable.

`Spring boot` offers properties `server.error.include-stacktrace` to include or not `stackTrace` on *whitelabel error page*. I would have some behavior on `API` for easily debugging during development phase.

Could be manage by [`JsonFilter`](http://wiki.fasterxml.com/JacksonFeatureJsonFilter) or something smarter.

**Comment by whiskeysierra** [comment]
The way we design our APIs is specified in our [API Guidelines](http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html#must-an-error-message-must-not-contain-the-stack-trace) where we have a specific section for this:

> # Must: An error message must not contain the stack trace. 
> The reasons:
>
> The API would leak implementation details to the outside world.
> Clients may not rely on pure API implementation details.

**Comment by kakawait** [comment]
Yeah I'm 100% ok with that for production! It was only for debugging/development instance.

By default stacktrace should be not display, but if there is a way to change the default behavior for certain condition it could be cool. 

Feel free to accept or not my needs, if you really think stacktrace should not display anyway ok

**Comment by whiskeysierra** [comment]
I'd assume if someone is developing a service locally that you have access to the log file and/or stdout. Wouldn't that be enough to see stacktraces?

**Comment by kakawait** [comment]
Except if you're not developing but debugging with old-school way or not direct access to the log files (on-premise) or internal first-level QA/integration environments that allow fast&dirty debugging when someone ping us. 

I have such situation but is related to my company processes (as developer I can't have access to QA env without asking an access grant). Maybe that why Spring created `server.error.include-stacktrace` (no source so be careful with that assumption)

It can be consider as edge case and not part of core. I can extend myself to fit that need for my use case instead. 

Close it if you're thinking is not a good thing to implement

**Comment by whiskeysierra** [comment]
> I have such situation but is related to my company processes & strategy (as developer I can't have access to QA env without asking an access grant).

Ok, I can see that being an issue.

> I can extend myself to fit that need for my use case instead.

I think the library in it's current form wouldn't allow to have this. We could change some interfaces though (AdviceTrait e.g.) to support this type of extension though.

**Comment by kakawait** [comment]
> I think the library in it's current form wouldn't allow to have this. We could change some interfaces though (AdviceTrait e.g.) to support this type of extension though.

Should we close issue?

I will try to read https://github.com/zalando/problem code deeply, I may success what I want with some Jackson configuration or trick without forking code (I really don't want to fork)!

**Comment by whiskeysierra** [comment]
> Should we close issue?

I'll have a look at it.

> I may success what I want with some Jackson configuration or trick to customize/filter

At that point you won't have access to the original exception anymore.

**Comment by whiskeysierra** [comment]
I opened zalando/problem#22 to add support for serialized stacktraces to the problem library. After that is merged and deployed I'll need to make use of the *cause* feature of problems to make the whole thing works. My idea is to generically convert exceptions to problems and nest them into each other using the `cause` property (pretty much like exception already) while every level has an array of stacktrace elements.

```yaml
{
  "type": "foo",
  "title": "foo",
  "status": 500,
  "stacktrace": [
    "org.example.Main.main(Main.java:27)",
    "..",
    ".."
  ],
  "cause": {
    "type": "bar",
    "title": "bar",
    "status": 500,
    "stacktrace": [
      "org.example.Main.main(Main.java:27)",
      "..",
      ".."
    ]
  }
}
```

**Comment by kakawait** [comment]
Ho yes great idea! You will totally cover all my needs, I really appreciate. I will able to remove our old Problem API implementation (not base on these projects) by ours/Zalando (I love the `Trait` concept)

Thanks so much.

**Comment by whiskeysierra** [comment]
@kakawait Do you want to take a look at #29?

**Comment by kakawait** [comment]
@whiskeysierra code looks perfect 👍  And It is a good idea to separate `stacktrace` and `causal chain` configuration.

**Comment by whiskeysierra** [comment]
@kakawait 0.6.0 is deployed to central. Happy coding!

**Comment by kakawait** [comment]
Lol I was just adding `0.6.0` release on our Nexus because I would try in advance! I can abort that.

Thank now just need to migrate old services 👍
