### ISSUE TITLE
ResponseStatusException not supported in problem-spring-web

### ISSUE THREAD

**Issue by BEllis** [zalando/problem-spring-web#275]
org.springframework.web.server.ResponseStatusException not supported in problem-spring-web

## Description
When an exception that extends org.springframework.web.server.ResponseStatusException is thrown, the HttpStatus is not honoured in the response and Problem JSON.

## Expected Behavior
In a controller method, when I throw an exception that extends org.springframework.web.server.ResponseStatusException I expect it to return a response with the HttpStatus specified in the exception.

## Actual Behavior
500 Internal Server Error response is always given and the problem JSON says the status is 500 instead of the one specified in the exception.

## Possible Fix
Handle ResponseStatusException in a similar fashion to the ResponseStatus annotation.

## Context
Some libraries we are using have exceptions that extend ResponseStatusException.

**Comment by cbornet** [comment]
The exception is already handled for Webflux. For MVC, the compatibility with Spring 4 should be checked if it's implemented.

**Comment by cbornet** [comment]
Note that it's easy to add an ExceptionHandler by yourself as a workaround.

**Comment by whiskeysierra** [comment]
I'll add a new default advice trait for this in the MVC part.
