### ISSUE TITLE
Issue in integrating with spring boot application

### ISSUE THREAD

**Issue by kkushal05** [zalando/problem-spring-web#286]
I integrated zalando problem API with my spring boot application (1.5.4), but I am not getting the response structure as per zalando. I have carefully made all changes as per h documentation on this github page/project(https://github.com/zalando/problem-spring-web). But, I am getting the default spring boot response as shown below.

Found:
{
 "timestamp": 1500597044204,
 "status": 400,
 "error": "Bad Request",
 "exception": "org.springframework.http.converter.BadRequestException",
 "message": "Bad Request : Incorrect ID",
 "path": "/birds"
}

But, the expected response is 
{
	"title": "Bad Request",
	"status": 400,
	"detail": "Incorrect ID"
}

**Comment by whiskeysierra** [comment]
Can you prepare a minimal example showcasing your issue?

**Comment by kkushal05** [comment]
I was able to make it work in my sprint boot application. But I found one challenge with using zalando problem api.

So to set some context about my application, I have a controller and service class.
In the normal approach, when we throw a custom RuntimeException in service class, the stack trace gets printed in logs and user sees the message that I pass as argument to my custom RuntimeException class. (like NotFoundException can be an example.)

Now if I use zalando with the first approach as mentioned in github page (using ConstraintViolationModule), I am not able to print stack strace in logs, which makes it difficult pinpoint  the method throwing the problem.

Also, the second approach of enabling stacktraces by registering a different ProblemModule is not suitable, as the stack strace is send to the user in response. We cannot let internal implementation details to be shared with the user.

**Comment by whiskeysierra** [comment]
> I am not able to print stack strace in logs, which makes it difficult pinpoint the method throwing the problem.

Every advice trait logs by default. See https://github.com/zalando/problem-spring-web/blob/master/problem-spring-web/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L123

Did you disable the logging by any chance?

**Comment by kkushal05** [comment]
Hi,

I have not disabled stacktrace. And also, this issue also exists with your spring web application on GitHub. It does not print the stack trace. 
Just prints the advice trait class name and message "Out of stock"

**Comment by kkushal05** [comment]
@whiskeysierra Please check my inputs.

**Comment by whiskeysierra** [comment]
Is it a 4xx error? Since those are not printed by default:

https://github.com/zalando/problem-spring-web/blob/f77f000fb22c3db0202e4130f54e9714cd40f20b/problem-spring-common/src/main/java/org/zalando/problem/spring/common/AdviceTraits.java#L30-L38

**Comment by kkushal05** [comment]
@whiskeysierra Is there some way of logging the stacktrace for 4xx errors also ?

**Comment by whiskeysierra** [comment]
Just override the `log` method in your advice.

**Comment by kkushal05** [comment]
@whiskeysierra Thanks for your input !!. So, should I create a new AdviceTrait or override the static log method in the controlleradvice class ?

**Comment by whiskeysierra** [comment]
I guess you have your own controller advice that inherits from ProblemHandling already. In that one, just override the log method:

```
public class ExceptionHandling implements ProblemHandling {
    // TODO override method here
}
```

**Comment by kkushal05** [comment]
@whiskeysierra I am using 0.23.0 version of prblem-spring--web and When I tried to override the log method, it shows a compile time error in the @Override annotation

@ControllerAdvice
public class ExceptionHandling implements ProblemHandling {

@Override
public static void log(){
.....................
}
}

**Comment by whiskeysierra** [comment]
That is the wrong signature. Let your IDE help you override it correctly. You're missing a couple of parameters like three exception and request. It also shouldn't be static.

**Comment by whiskeysierra** [comment]
I'm closing this. Let me know if this didn't fix it for you.

**Comment by kkushal05** [comment]
@whiskeysierra  

Sorry for the delay.

I attempted the approach you suggested, but the 0.22.0 version of spring web does not recognize any log method which can be overriden. Also, I have spring tools suite as IDE and I tried mentioning the log method as shown below

Note ; Ignore the  "@override" below. Githug interpreted that as some userId hence auto converted "@Override" to  "@override".

Further, just to brief my objective again "I want to log  4xx and 5xx status codes as errors".

@ControllerAdvice
public class ExceptionHandling implements ProblemHandling {

@override
public void log(){
.....................
}
}

**Comment by whiskeysierra** [comment]
```java
@ControllerAdvice
public class ExceptionHandling implements ProblemHandling {

    @zalando/open-source-review-group }
    public void log(
            final Throwable throwable, final Problem problem,
            final NativeWebRequest request, final HttpStatus status) {

        if (status.is4xxClientError() || status.is5xxServerError()) {
            LOG.error(status.getReasonPhrase(), throwable);
        }
    }

}
```

**Comment by kkushal05** [comment]
@whiskeysierra It worked..Appreciate your support !!
