### ISSUE TITLE
Handle javax.validation.ConstraintViolationException

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#3]
Right now only the Spring specific ``MethodArgumentNotValidException`` is handled, might be useful to handle ``ConstraintViolationException`` of ``javax.validation`` - which would add a dependency (or have it optional?)

**Comment by lukasniemeier-zalando** [comment]
``ConstraintViolationException`` is thrown by the [``MethodValidationInterceptor``](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/validation/beanvalidation/MethodValidationInterceptor.html), which matches on classes or method arguments annotated with [``@Validated``](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/validation/annotation/Validated.html) (see [``MethodValidationPostProcessor``](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/validation/beanvalidation/MethodValidationPostProcessor.html)).

**Comment by lukasniemeier-zalando** [comment]
So to summarize:

```java
@Validated  // needed to actually trigger validation
@RestController
class MyController {
  
  @RequestMapping
  Response serve(
    @RequestParam @Min(2) Integer parameter,  // throws ConstraintViolationException
    @RequestBody @Valid BodyModel body        // throws MethodArgumentNotValidException
    ) {
      return new Response();
    }

}

**Comment by jhorstmann** [comment]
Sounds strange for spring to be throwing different exceptions in both cases. A dependency on `javax.validation:validation-api` should be fine as `spring-web` already has at least a compile time dependency on it.

**Comment by whiskeysierra** [comment]
@RequestParam @Min(2) Integer parameter,  // throws ConstraintViolationException
    @RequestBody @Valid BodyModel body        // throws MethodArgumentNotValidException

![Facepalm](http://4.bp.blogspot.com/-m2slla6Qc4o/Uk2nq4In5GI/AAAAAAAAE0w/BVWz6YNrgj4/s1600/picard-facepalm-o.gif)

**Comment by whiskeysierra** [comment]
I tried to write a test and implementation for the ConstraintViolationException case (see #4):

    @RequestParam @Min(2) Integer parameter,  // throws ConstraintViolationException

But I couldn't get it to work. According to [this Spring issue](https://jira.spring.io/browse/SPR-6380), it's not supposed to work. But I'm fairly certain I've seen this exception before.

**Comment by lukasniemeier-zalando** [comment]
Hm strange - I've actually created the class shown in my previous example and played around with the annotations to understand what Spring is doing there.

**Comment by lukasniemeier-zalando** [comment]
Fixed by #4

**Comment by edwmamedov** [comment]
What is the reason of this behavior, how to fix this? Thanks in advance.

**Comment by whiskeysierra** [comment]
@edwmamedov Spring's behaviour?

**Comment by edwmamedov** [comment]
@whiskeysierra yep. 
BTW swagger 2.8.0 solved this bug.
