### ISSUE TITLE
Release 0.24.0 Requires Spring 5 

### ISSUE THREAD

**Issue by jbspeakr** [zalando/problem-spring-web#304]
## Description
Although introduced in a minor version change, the ["Added support for ResponseStatusException"](https://github.com/zalando/problem-spring-web/commits/fda7e8443e2434a629e20207b237e119ee2cb537/problem-spring-web/src/main/java/org/zalando/problem/spring/web/advice/general/ResponseStatusAdviceTrait.java) results in a major incompatibility issue as problem-spring-web now requires Spring 5.0 or greater because [ResponseStatusException was just introduced with Spring 5.0](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/server/ResponseStatusException.html). 

## Expected Behavior
There are no major incompatibilities introduced in a non-major version change. Updating a library to a newer minor version should not require to upgrade major versions of underlying frameworks.

## Actual Behavior
Updating problem-spring-web from 0.23.0 to 0.24.0 results in `java.lang.ClassNotFoundException: org.springframework.web.server.ResponseStatusException`. 

## Possible Fix
- Support Spring5 conditionally without breaking compatibility to Spring4 or
- Introduce hard Spring5 requirement in a new major version 

## Steps to Reproduce
1. Take a SpringBoot 1.5.x application
2. Introduce problem-spring-web 0.24.0
3. Startup Context

## Context
Our plan was to simply update to latest 0.x minor version to see whether it fixes another problem we ran into when using problem-spring-web together with springboot.

**Comment by jbspeakr** [comment]
PS: I know the new requirement towards Spring5 (and hence SpringBoot2) is documented in the readme. However, the current versioning does not reflect that. Also it's not transparent that Spring4 is not supported anymore.

**Comment by jbspeakr** [comment]
PPS: I know [Spring 1.5.x is EOL in August](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019) and that we should upgrade anyway. Reflecting major incompatibilities in versions is a good idea anyway ;D

**Comment by whiskeysierra** [comment]
> There are no major incompatibilities introduced in a non-major version change. Updating a library to a newer minor version should not require to upgrade major versions of underlying frameworks.

Technically...

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
>
> https://semver.org/#spec-item-4

I'll update the readme to give a strong hint about compatibility.

**Comment by lukasniemeier-zalando** [comment]
Maybe it's time for a `1.0.0` release :wink:
