### ISSUE TITLE
Easier decorating of problem builder with data from native web request

### ISSUE THREAD

**Issue by binkley** [zalando/problem-spring-web#308]
It would be helpful for there to be additional hooks for customization to decorate the problem builder based on data from `NativeWebRequest`.

## Detailed Description

I'm decorating building of problems with data from `NativeWebRequest`, for example, the original request method and URL, and there is more to override than I expected, especially given the clean design of Problem library.

Pain points:

* Replacing calls of `toProblem(throwable)` and its variants with `toProblem(throwable, request)` and matching variants in each of the relevant `create(...)` overrides
* `ResponseStatusAdapter` is default scope, not `public`, so inaccessible; work around is to use `toProblem(throwable).getStatus()` from within override of `create(throwable, request)`

## Context

While working with our QAs and our DevOps team, tracking down issues with remote service calls (microservice architecture) is tricky, and not always clear why a particular call fails.

It was helpful to _overprovide information_, to aid human eyes in spotting root causes of issues.

It was also helpful for automated scripting in performing analysis.  (We use JSON logging in production, so having common JSON shapes in problem payloads for all remote service calls is a win.)

## Possible Implementation

Using version 0.24 of the Spring integration for Problem, we wound up with these overrides and replacement methods (below).  Key changes:

* Alternative `toProblem(throwable, ...)` methods that take a `NativeWebRequest` argument, ie, `toProblem(throwable, request, ...)`
* Using the alternatives, the key "hook" method is `toProblem(throwable, request, status, type)` where we call `extra(throwable, request, status)`, and add the returned map to the problem parameters

```
    @Override
    public ResponseEntity<Problem> create(final Throwable throwable,
            final NativeWebRequest request) {
        final ThrowableProblem problem = toProblem(throwable, request,
                toProblem(throwable).getStatus());
        return create(throwable, problem, request);
    }

    private ThrowableProblem toProblem(final Throwable throwable,
            final NativeWebRequest request, final StatusType status) {
        return toProblem(throwable, request, status, Problem.DEFAULT_TYPE);
    }

    private ThrowableProblem toProblem(final Throwable throwable,
            final NativeWebRequest request, final StatusType status,
            final URI type) {
        final var problemBuilder = prepare(throwable, status, type);
        extra(throwable, status.getStatusCode(), request)
                .forEach(problemBuilder::with);
        final ThrowableProblem problem = problemBuilder.build();
        final StackTraceElement[] stackTrace = createStackTrace(throwable);
        problem.setStackTrace(stackTrace);
        return problem;
    }

    @Override
    public ResponseEntity<Problem> create(final StatusType status,
            final Throwable throwable, final NativeWebRequest request,
            final HttpHeaders headers) {
        return create(throwable, toProblem(throwable, request, status),
                request, headers);
    }

    @Override
    public ResponseEntity<Problem> create(final StatusType status,
            final Throwable throwable, final NativeWebRequest request,
            final HttpHeaders headers, final URI type) {
        return create(throwable, toProblem(throwable, request, status, type),
                request, headers);
    }
```

## Your Environment

* Version used: 0.24
* Link to your project: https://github.com/binkley/spikes/tree/master/spring-boot-logging

This is not our actual project (private, commercial client), but a public spike repository for trying out better approaches, in this case, managing complex logging requirements in Spring Boot, microservices, and the Cloud.

**Comment by cbornet** [comment]
In JHipster, we do it by overloading the `process`method. See for instance https://github.com/jhipster/jhipster-sample-app/blob/master/src/main/java/io/github/jhipster/sample/web/rest/errors/ExceptionTranslator.java#L58
I agree that it is not ideal though since the Problem has already been built and we need to copy its fields to a new ProblemBuilder.

**Comment by whiskeysierra** [comment]
> I'm decorating building of problems with data from `NativeWebRequest`, for example, the original request method and URL

We solved that particular issue by using log correlation ids, e.g. when logging requests/responses with logbook: https://github.com/zalando/logbook/blob/master/docs/scalyr.md

At Zalando we use scalyr as for log shipping and indexing which has a nice support to basically copy over fields from one log event to another in case they correlate.

**Comment by whiskeysierra** [comment]
Is this still needed? @binkley

**Comment by binkley** [comment]
@whiskeysierra I've moved from this project some while back (I work for clients).   The extension point makes sense in the context described.  I'd like to give the above alternatives a go, given a project!  :(

I'd say close this for now, and reopen which if it crops up again.
