### ISSUE TITLE
Why not support generics

### ISSUE THREAD

**Issue by SingleDispatcher** [zalando/problem-spring-web#310]
for example : protected <T> Problem<T> createSuccessWithData(T data);

**Comment by SingleDispatcher** [comment]
protected <T> Problem<T> createSuccessWithData(T data);

**Comment by SingleDispatcher** [comment]
protected 《T》Problem《T》 createSuccessWithData(T data);

**Comment by whiskeysierra** [comment]
What kind of data would that be? How should the response in JSON look like?

**Comment by SingleDispatcher** [comment]
> What kind of data would that be? How should the response in JSON look like?

I hope there is no escaping in RPC.

**Comment by whiskeysierra** [comment]
I don't get it
