### ISSUE TITLE
How to extend the built-in problemtypes for all advicetraits?

### ISSUE THREAD

**Issue by jgoldhammer** [zalando/problem-spring-web#32]
Hi,

I want to use your library and want to enrich each problem returned for standard spring errors with more information like a problem-id which is logged in the background with some more information.
How can I do that? I don´t see any possibility
Currently I have to include your sourcecode into my project and adapt the code to my needs...

Thanks,
Jens

**Comment by whiskeysierra** [comment]
Every problem is being constructed in this method https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L98

Since it's a default method in an interface you can override it:

```java
@ControllerAdvice
public class ExceptionHandling implements ProblemHandling {

    public ThrowableProblem toProblem(final Throwable throwable, final StatusType status) {
        // TODO implement
    }

}
```

Would that work for you?

**Comment by jgoldhammer** [comment]
Thanks for the quick response. 
I want to overwrite the problem creation for all built-in traits. Is this possible with this implementation? Sorry, it is not clear for me.

**Comment by whiskeysierra** [comment]
Yes, if you check the source code you'll see that all traits finally delegate to this single method for creating a problem instance. (Only exception is if your controller method already throws a problem.)

**Comment by jgoldhammer** [comment]
Thanks, it works for me!!
