### ISSUE TITLE
Zalando Spring Web Problem SecurityConfiguration should disable defaults

### ISSUE THREAD

**Issue by bertramn** [zalando/problem-spring-web#359]
The Zalando Spring Web Problem [`SecurityConfiguration`](https://github.com/zalando/problem-spring-web/blob/master/problem-spring-web-autoconfigure/src/main/java/org/zalando/problem/spring/web/autoconfigure/security/SecurityConfiguration.java) should disable the default configuration of the Spring Security chain to avoid pre-setting senseless defaults that will have to be undone in another `WebSecurityConfigurerAdapter` by the developer.

## Description

The current Zalando Spring Web Problem `SecurityConfiguration` extends the `WebSecurityConfigurerAdapter`, which [by default](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L123) will automatically configure the `HttpSecurity` context with what some deem sensible defaults. Unfortunately these defaults are not always sensible e.g. Stateless REST APIs do not have any login or logout mechanisms and require a specific session management configuration. 

Disabling the defaults in the `SecurityConfiguration` class will ensure [this](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L208) `if` block is not executed during configuration, making it much easier for a developer to properly configure the security chain.

## Expected Behavior

The Zalando Spring Web Problem `SecurityConfiguration` should not configure any parts of the `HttpSecurity` configuration other than `http.exceptionHandling()`.

## Actual Behavior

The current implementation also triggers [this default configuration block](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L208) in the parent class that is highly undesirable for some uses of Spring Boot.

## Possible Fix

Ensure the implementing class disables defaults in the super constructor:

```java

public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

  public SecurityConfiguration() {
    super(true);
  }
...
}
````

## Steps to Reproduce

conceptual issue

## Context

A developer will have to create another `WebSecurityConfigurerAdapter` and reset default values such as CSRF, login, logout etc. Whilst doing this, one has to take extra care to ensure the "undoing" configuration is ordered correctly with additional annotations. Misconfigurations can be hard to debug.

## Your Environment
* Version used: 0.25.0

**Comment by whiskeysierra** [comment]
See #360

**Comment by bertramn** [comment]
I have done some more debugging and it appears that it is not possible to configure spring security the way it is currently suggested. The introduction of `org.zalando.problem.spring.web.autoconfigure.security.SecurityConfiguration` will cause 2 security configurers configuring 2 security filter chains that will apply it's configured filters separately. Given the `SecurityConfiguration` extends `WebSecurityConfigurerAdapter` it will also inherently [configure unwanted](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L210) (for us) defaults such as the `CsrfFilter`. I am not sure what can be done from a spring security perspective to "merge" security configurers but current solution is not workable if one wants to disable things like csrf(), logout() and other defaults that are applied in the [`WebSecurityConfigurerAdapter`](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L210).

**Comment by whiskeysierra** [comment]
So what's the best course of action here?

**Comment by bertramn** [comment]
One thing is for sure, you cannot have SecurityConfiguration extend WebSecurityConfigurerAdapter. There seems to be [some provisions](https://github.com/spring-projects/spring-security/blob/5.1.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L224-L229) and the [Spring Security doco](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#jc-custom-dsls) seems to suggest that a custom configurer (init method) would be more appropriate for your case than using the WebSecurityConfigurerAdapter. But I have not tried that apporach yet.

**Comment by bertramn** [comment]
Also there is a configuration race condition in `JacksonModulesRegistrator`, it needs to be run before JacksonAutoConfguration or else you end up with an ObjectMapper injected into the message converter that does not include any of the ProblemModules ... after restarts I did receive properly formatted problem response JSON at random and at other times just a dump of raw bean properties.

```java
@AutoConfigureBefore({
    JacksonAutoConfiguration.class
})
public class JacksonModulesRegistrator {
...
```
