### ISSUE TITLE
Make org.zalando.problem.violations.Violation non final? 

### ISSUE THREAD

**Issue by JoergAdler** [zalando/problem-spring-web#379]
Hi, 
first: Thanks for your great library it saved me a lot of time already. 

As I use the part with ContraintViolations very often, I wondered if there is a possibility to have the org.zalando.problem.violations.Violation non final? 

So one can include more detail in the returned entity. e.g. if a Max constraint is violated, one sends the violated bound in an extra property along with the response.

Maybe there is already another way to achieve this?

**Comment by whiskeysierra** [comment]
https://fasterxml.github.io/jackson-annotations/javadoc/2.2.0/com/fasterxml/jackson/annotation/JsonUnwrapped.html might be a good alternative to do that. Generally speaking I'd say it's better to roll your own. Constraint violation problem is really very primitive.

**Comment by JoergAdler** [comment]
The problem would be: where to put the JsonUnwrap? As org.zalando.problem.violations.Violation is used in every API, one can implement for ContraintViolations.

**Comment by JoergAdler** [comment]
e.g. it would help if I could create here my own subclass of the class
```
public class BindingResultAdviceTrait implements ProblemHandling, BaseBindingResultAdviceTrait {

    @Override
    public Violation createViolation(final FieldError error) {
        final String fieldName = formatFieldName(error.getField());
        return new Violation(fieldName, error.getCode());
    }
}
```

**Comment by JoergAdler** [comment]
What's wrong with inheritance in this place? 
As the return type is Violation, one has to inherit from this. 

Another advantage of this is to not break any existing API and be way more flexible.
