### ISSUE TITLE
Provide configuration option for omitting Throwable messages from Problems constructed by default Traits

### ISSUE THREAD

**Issue by mryangza** [zalando/problem-spring-web#381]
The default Problem constructed for a Throwable includes the message from the Throwable in the detail parameter. This may include implementation details (e.g. parts of the stack trace) thereby leaking out implementation details to the client. It would be awesome if this was configurable and the detail parameter could be optionally omitted.

## Detailed Description
In the `org.zalando.problem.spring.common.AdviceTrait.prepare(Throwable, StatusType, URI)` method the Problem is constructed with a detail of `Throwable.getMessage()`. For some (lots) of standard Spring exceptions, this includes class details. For example for a `org.springframework.http.converter.HttpMessageNotReadableException` you get something like this:

```
{
    "title": "Bad Request",
    "status": 400,
    "detail": "Required request body is missing: public org.springframework.util.concurrent.ListenableFuture<org.springframework.http.ResponseEntity<java.util.List<my.pkg.MyClass>>> my.pkg.Controller.getStuff(my.pk.MyDTO)"
}
```

This leaks out information about the API implementation. This is a similar / the same rationale as for making stack traces configurable.

## Context
In production code we'd disable using messages from Throwables in the detail parameter to avoid this leakage. This information isn't useful for the client of the API. The message would still be available in log files so for reference by the API developers.

## Your Environment
* Version used: 0.25.0

**Comment by whiskeysierra** [comment]
As a workaround it's always an option to just override those methods and implement it yourself.

**Comment by mryangza** [comment]
(Sorry for open -> close -> reopen ... finger slipped)

> As a workaround it's always an option to just override those methods and implement it yourself.

Thanks for the input - in fact, that's what I am doing and it works great. I was a bit hesitant to override `prepare` in case one of the `toProblem` methods (in the future) starts calling something else to prepare the ProblemBuilder.

**Comment by whiskeysierra** [comment]
> `` in case one of the `toProblem` methods (in the future) starts calling something else to prepare the ProblemBuilder.

That would be a breaking change. The only reason why those methods are public and non-final is to be overridden to customize the processing.

**Comment by whiskeysierra** [comment]
If that is good enough for you I'd close this issue. Alternatively you could prepare a pull request e.g. introducing a new method that returns a boolean to change that behavior.
