### ISSUE TITLE
Violation url customization

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#40]
I really love `ViolationAdviceTrait` however do you think is possible to customize url https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/validation/ConstraintViolationProblem.java#L37 ?

**Comment by whiskeysierra** [comment]
I'd argue that only one definition of a specific problem type should exist. But I could see why someone would resist to use something which contains a foreign company name :wink: 

Side note: We consider to create a github page, see zalando/problem#17. That would move the page to https://zalando.github.io/problem/constraint-violation. But I think that won't fix your concern.

**Comment by kakawait** [comment]
Yeah my company is not so "open-mind" related to *foreign company name* and we also deliver on-premise product and we cannot expect that client will be connected to internet.

I'm ok for your point of view, I will simply override what I need if I really need to change URL.

**Comment by whiskeysierra** [comment]
> we cannot expect that client will be connected to internet

It's not needed, in theory. At least not from the application itself. A developer might want to look at it though.

> I'm ok with your point of view. So no problem for won't fix, I will simply override what I need if I really need (I'm a bit lazy to override just for an URL :)) to change URL.

I think the cleanest way would be provide a method that is used, rather than a constant. So implementations can override, if desired.

I'm still not 100% convinced that it's the right thing to do though.

**Comment by kakawait** [comment]
> It's not needed, in theory. At least not from the application itself. A developer might want to look at it though.

I was just thinking about that after pressing send "comment" button.

> I'm still not 100% convinced that it's the right thing to do though.

BTW is not really a big deal for me, so if you consider is cleaner to keep static URL I'm ok

**Comment by galvo** [comment]
It would be useful to override this URL also, it makes more sense for the URL to be under the control of the applications/company providing this. Could be an optional overridable spring property
