### ISSUE TITLE
How can I log exception managed by ProblemHandling

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#41]
_Maybe stupid question_ but if I would log every exceptions (for auditing?), is there any way to achieve that without overriding each `Trait`?

**Comment by whiskeysierra** [comment]
Good question. Right now, as a workaround, I'd suggest to override only [`AdviceTrait.toProblem(Throwable, StatusType)`](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L98).

**Comment by kakawait** [comment]
I think this workaround is a solution, not only a workaround. For my point of view is totally acceptable.

Again thank you.

PS: I finish migration from custom to _Zalando_ `problem-spring-mvc` 👍  Is pleasure to use this lib

**Comment by whiskeysierra** [comment]
> I think this workaround is a solution, not only a workaround.

I'm not 100% sure that it covers all cases. I think if you already throw a `Problem` it won't be seen there.

> Is pleasure to use this lib

Glad to hear :grinning:

**Comment by whiskeysierra** [comment]
Note to self: Take a look at Spring's ResponseEntityExceptionHandler and shamelessly copy stuff that looks useful, e.g.:

```java
if (HttpStatus.INTERNAL_SERVER_ERROR.equals(status)) {
    request.setAttribute(WebUtils.ERROR_EXCEPTION_ATTRIBUTE, ex, WebRequest.SCOPE_REQUEST);
}
```

as well as logging support

**Comment by whiskeysierra** [comment]
We just realized that this probably breaks AppDynamics because we're not setting that attribute, so we don't see any stacktraces.

**Comment by kakawait** [comment]
Didn't know *AppDynamics* but nice if I can also fix a bug from your part 👍

**Comment by areguig** [comment]
Surely stupid, but do you have any example where the exceptions are logged ?
