### ISSUE TITLE
SpringBoot v2.2.1.RELEASE along with problem-spring-web-starter 0.25.1 gives back stack trace on Constraint Violation

### ISSUE THREAD

**Issue by smfaizalkhan** [zalando/problem-spring-web#414]
I like the RFC 7807 specification and tried to implement in out project and decide to go on with problem spring web of zalando.

As per the doc ,added [Dependancy](https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web#spring-boot)  starter module to dependencies

 <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>problem-spring-web-starter</artifactId>
            <version>0.25.1</version>
        </dependency>

And for the configuration information
[Config](https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web#configuration)

If not using the starter module, make sure you register the required modules with your ObjectMapper: 

As we are using started module we didn't give any configuration for objectMapper and went with default implementation of traits.

But we get the whole stacktrace

{
    "cause": null,
    "stackTrace": [
        {
            "methodName": "newConstraintViolationProblem",
            "fileName": "BaseValidationAdviceTrait.java",
            "lineNumber": 50,
            "className": "org.zalando.problem.spring.web.advice.validation.BaseValidationAdviceTrait",
            "nativeMethod": false
        },
        {
            "methodName": "handleConstraintViolation",
            "fileName": "ConstraintViolationAdviceTrait.java",
            "lineNumber": 39,
            "className": "org.zalando.problem.spring.web.advice.validation.ConstraintViolationAdviceTrait",
            "nativeMethod": false
        },
        {
            "methodName": "invoke0",
            "fileName": "NativeMethodAccessorImpl.java",
            "lineNumber": -2,
            "className": "sun.reflect.NativeMethodAccessorImpl",
            "nativeMethod": true
        },
        {
            "methodName": "invoke",
            "fileName": "NativeMethodAccessorImpl.java",
            "lineNumber": 62,
            "className": "sun.reflect.NativeMethodAccessorImpl",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "DelegatingMethodAccessorImpl.java",
            "lineNumber": 43,
            "className": "sun.reflect.DelegatingMethodAccessorImpl",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "Method.java",
            "lineNumber": 498,
            "className": "java.lang.reflect.Method",
            "nativeMethod": false
        },
        {
            "methodName": "doInvoke",
            "fileName": "InvocableHandlerMethod.java",
            "lineNumber": 190,
            "className": "org.springframework.web.method.support.InvocableHandlerMethod",
            "nativeMethod": false
        },
        {
            "methodName": "invokeForRequest",
            "fileName": "InvocableHandlerMethod.java",
            "lineNumber": 138,
            "className": "org.springframework.web.method.support.InvocableHandlerMethod",
            "nativeMethod": false
        },
        {
            "methodName": "invokeAndHandle",
            "fileName": "ServletInvocableHandlerMethod.java",
            "lineNumber": 106,
            "className": "org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod",
            "nativeMethod": false
        },
        {
            "methodName": "doResolveHandlerMethodException",
            "fileName": "ExceptionHandlerExceptionResolver.java",
            "lineNumber": 407,
            "className": "org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver",
            "nativeMethod": false
        },
        {
            "methodName": "doResolveException",
            "fileName": "AbstractHandlerMethodExceptionResolver.java",
            "lineNumber": 61,
            "className": "org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver",
            "nativeMethod": false
        },
        {
            "methodName": "resolveException",
            "fileName": "AbstractHandlerExceptionResolver.java",
            "lineNumber": 141,
            "className": "org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver",
            "nativeMethod": false
        },
        {
            "methodName": "resolveException",
            "fileName": "HandlerExceptionResolverComposite.java",
            "lineNumber": 80,
            "className": "org.springframework.web.servlet.handler.HandlerExceptionResolverComposite",
            "nativeMethod": false
        },
        {
            "methodName": "processHandlerException",
            "fileName": "DispatcherServlet.java",
            "lineNumber": 1300,
            "className": "org.springframework.web.servlet.DispatcherServlet",
            "nativeMethod": false
        },
        {
            "methodName": "processDispatchResult",
            "fileName": "DispatcherServlet.java",
            "lineNumber": 1111,
            "className": "org.springframework.web.servlet.DispatcherServlet",
            "nativeMethod": false
        },
        {
            "methodName": "doDispatch",
            "fileName": "DispatcherServlet.java",
            "lineNumber": 1057,
            "className": "org.springframework.web.servlet.DispatcherServlet",
            "nativeMethod": false
        },
        {
            "methodName": "doService",
            "fileName": "DispatcherServlet.java",
            "lineNumber": 943,
            "className": "org.springframework.web.servlet.DispatcherServlet",
            "nativeMethod": false
        },
        {
            "methodName": "processRequest",
            "fileName": "FrameworkServlet.java",
            "lineNumber": 1006,
            "className": "org.springframework.web.servlet.FrameworkServlet",
            "nativeMethod": false
        },
        {
            "methodName": "doGet",
            "fileName": "FrameworkServlet.java",
            "lineNumber": 898,
            "className": "org.springframework.web.servlet.FrameworkServlet",
            "nativeMethod": false
        },
        {
            "methodName": "service",
            "fileName": "HttpServlet.java",
            "lineNumber": 634,
            "className": "javax.servlet.http.HttpServlet",
            "nativeMethod": false
        },
        {
            "methodName": "service",
            "fileName": "FrameworkServlet.java",
            "lineNumber": 883,
            "className": "org.springframework.web.servlet.FrameworkServlet",
            "nativeMethod": false
        },
        {
            "methodName": "service",
            "fileName": "HttpServlet.java",
            "lineNumber": 741,
            "className": "javax.servlet.http.HttpServlet",
            "nativeMethod": false
        },
        {
            "methodName": "internalDoFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 231,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "doFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 166,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "doFilter",
            "fileName": "WsFilter.java",
            "lineNumber": 53,
            "className": "org.apache.tomcat.websocket.server.WsFilter",
            "nativeMethod": false
        },
        {
            "methodName": "internalDoFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 193,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "doFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 166,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "doFilterInternal",
            "fileName": "CharacterEncodingFilter.java",
            "lineNumber": 201,
            "className": "org.springframework.web.filter.CharacterEncodingFilter",
            "nativeMethod": false
        },
        {
            "methodName": "doFilter",
            "fileName": "OncePerRequestFilter.java",
            "lineNumber": 119,
            "className": "org.springframework.web.filter.OncePerRequestFilter",
            "nativeMethod": false
        },
        {
            "methodName": "internalDoFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 193,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "doFilter",
            "fileName": "ApplicationFilterChain.java",
            "lineNumber": 166,
            "className": "org.apache.catalina.core.ApplicationFilterChain",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "StandardWrapperValve.java",
            "lineNumber": 202,
            "className": "org.apache.catalina.core.StandardWrapperValve",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "StandardContextValve.java",
            "lineNumber": 96,
            "className": "org.apache.catalina.core.StandardContextValve",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "AuthenticatorBase.java",
            "lineNumber": 526,
            "className": "org.apache.catalina.authenticator.AuthenticatorBase",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "StandardHostValve.java",
            "lineNumber": 139,
            "className": "org.apache.catalina.core.StandardHostValve",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "ErrorReportValve.java",
            "lineNumber": 92,
            "className": "org.apache.catalina.valves.ErrorReportValve",
            "nativeMethod": false
        },
        {
            "methodName": "invoke",
            "fileName": "StandardEngineValve.java",
            "lineNumber": 74,
            "className": "org.apache.catalina.core.StandardEngineValve",
            "nativeMethod": false
        },
        {
            "methodName": "service",
            "fileName": "CoyoteAdapter.java",
            "lineNumber": 343,
            "className": "org.apache.catalina.connector.CoyoteAdapter",
            "nativeMethod": false
        },
        {
            "methodName": "service",
            "fileName": "Http11Processor.java",
            "lineNumber": 408,
            "className": "org.apache.coyote.http11.Http11Processor",
            "nativeMethod": false
        },
        {
            "methodName": "process",
            "fileName": "AbstractProcessorLight.java",
            "lineNumber": 66,
            "className": "org.apache.coyote.AbstractProcessorLight",
            "nativeMethod": false
        },
        {
            "methodName": "process",
            "fileName": "AbstractProtocol.java",
            "lineNumber": 861,
            "className": "org.apache.coyote.AbstractProtocol$ConnectionHandler",
            "nativeMethod": false
        },
        {
            "methodName": "doRun",
            "fileName": "NioEndpoint.java",
            "lineNumber": 1579,
            "className": "org.apache.tomcat.util.net.NioEndpoint$SocketProcessor",
            "nativeMethod": false
        },
        {
            "methodName": "run",
            "fileName": "SocketProcessorBase.java",
            "lineNumber": 49,
            "className": "org.apache.tomcat.util.net.SocketProcessorBase",
            "nativeMethod": false
        },
        {
            "methodName": "runWorker",
            "fileName": "ThreadPoolExecutor.java",
            "lineNumber": 1149,
            "className": "java.util.concurrent.ThreadPoolExecutor",
            "nativeMethod": false
        },
        {
            "methodName": "run",
            "fileName": "ThreadPoolExecutor.java",
            "lineNumber": 624,
            "className": "java.util.concurrent.ThreadPoolExecutor$Worker",
            "nativeMethod": false
        },
        {
            "methodName": "run",
            "fileName": "TaskThread.java",
            "lineNumber": 61,
            "className": "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable",
            "nativeMethod": false
        },
        {
            "methodName": "run",
            "fileName": "Thread.java",
            "lineNumber": 748,
            "className": "java.lang.Thread",
            "nativeMethod": false
        }
    ],
    "type": "https://zalando.github.io/problem/constraint-violation",
    "status": "BAD_REQUEST",
    "violations": [
        {
            "field": "xxxxx",
            "message": "xxxx"
        }
    ],
    "title": "Constraint Violation",
    "message": "Constraint Violation",
    "instance": null,
    "parameters": {},
    "detail": null,
    "localizedMessage": "Constraint Violation",
    "suppressed": []
}

Please advice is anything  is missing from our side ?

**Comment by smfaizalkhan** [comment]
@whiskeysierra 
While Debugging noticed that the Class "ConstraintViolationProblem" calls the 
"ThrowableProblem "as it extends it ,we get the below code executed and displayed in the response

  protected ThrowableProblem(@Nullable final ThrowableProblem cause) {
        super(cause);
        Collection<StackTraceElement> stackTrace = StackTraceProcessor.COMPOUND.process(Arrays.asList(this.getStackTrace()));
        this.setStackTrace((StackTraceElement[])stackTrace.toArray(new StackTraceElement[stackTrace.size()]));
    }

As by default the stacktrace is disabled and we haven't configured any ,i would expect either 

Code not executed or stacktrace not as part of the response.

Regards,
Faizal

**Comment by whiskeysierra** [comment]
The kind of output that you posted is caused by a missing module registration of `ProblemModule` (and `ConstraintViolationProblemModule`). Either the modules are not registered at all or on the wrong mapper or the mapper is not used in Web Mvc.

Do you have `@EnableWebMvc` anywhere by any chance?

**Comment by smfaizalkhan** [comment]
@whiskeysierra 

Thanks for the response,Please find the responses below

1) Either the modules are not registered
    It is registered, if not  we should have got Bean Not Found Exception when problemModule is 
     invoked .we  didn't get this error
   
2) on the wrong mapper or the mapper is not used in Web Mvc
        we didn't configure the bean bcoz as per the doc [Configuration](https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web#configuration)
   it is part of the starter module

3) Do you have @EnableWebMvc anywhere by any chance
     No,a normal @SpringBootApplication 

 the dependancy added is 

      <dependency>
                <groupId>org.zalando</groupId>
                <artifactId>problem-spring-web-starter</artifactId>
                <version>0.25.1</version>
            </dependency>

Regards,
Faizal

**Comment by whiskeysierra** [comment]
>     1. It is registered, if not  we should have got Bean Not Found Exception when problemModule is
>        invoked .we  didn't get this error

Nope. Jackson's ObjectMapper just won't have registered. There wouldn't be an exception.

You need to figure out:

- Which ObjectMapper is serializing your responses?
- Where is it configured?
- Is the ProblemModule is registered?

**Comment by smfaizalkhan** [comment]
@whiskeysierra 

Thanks for the response.

- Which ObjectMapper is serializing your responses?
        Default JacksonAutoConfiguration from Spring 

- Where is it configured?
    From spring Context

- Is the ProblemModule is registered?
   Now that we figured we configured it in the beans

         @Bean
            public Jackson2ObjectMapperBuilderCustomizer jacksonBuilder() {
                 return (Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder)  ->
                jacksonObjectMapperBuilder.modules(new ProblemModule());
               }
  

On debugging we see that the default ProblemModule constructor is invoked

    @SafeVarargs
    public <E extends Enum & StatusType> ProblemModule(final Class<? extends E>... types) throws IllegalArgumentException {
        this(false, buildIndex(types));
    }

But still we get the stacktrace

**Comment by whiskeysierra** [comment]
> Now that we figured we configured it in the beans

That shouldn't be needed.

> On debugging we see that the default ProblemModule constructor is invoked

Could still be that there are two object mappers and that your response is being serialized with another one.

**Comment by smfaizalkhan** [comment]
> That shouldn't be needed.
  
Without this config ProblemModule is not registered.
 
> Could still be that there are two object mappers and that your response is being serialized with 
     another one.

   No we have only the spring offered jackson objectMapper (com.fasterxml.jackson.databind)
 which is part of the  (spring-boot-starter-web) dependancy and used by spring JacksonAutoConfiguration

**Comment by whiskeysierra** [comment]
> Without this config ProblemModule is not registered.

But that's what the auto configuration is for.

**Comment by smfaizalkhan** [comment]
@whiskeysierra 

You were right , Below are the answers for your questions
 

-  **Which ObjectMapper is serializing your responses?**
     Swagger Configs default ObjectMapper was deserializing

-    **Do you have @EnableWebMvc anywhere by any chance?**

     By mistake they were extending the WebMvcConfigurationSupport
      and so had to override the 

     @Override
    protected void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
      }


So i removed it and then it was bingo..
Thanks for your sughgestions
