### ISSUE TITLE
Swagger Response for Documentation

### ISSUE THREAD

**Issue by smfaizalkhan** [zalando/problem-spring-web#416]
Swagger Response for Documentation

## Description
We use few custom trait and few of the shelf traits from problem api, Proper usage of traits for Swagger

## Expected Behavior
Would like to see how to use these traits for Swagger Documentation

## Steps to Reproduce

1. We have few custom traits like below

 public interface XXXXXAdviceTrait extends AdviceTrait,BaseProblemBuilder {

    
    @ExceptionHandler
    default ResponseEntity<Problem> handleGraphQLException(final GraphQLException exception, final NativeWebRequest request) {
        ResponseEntity<Problem> responseEntity =  create(Status.INTERNAL_SERVER_ERROR, exception, request);
        
        Problem problem = responseEntity.getBody();
        ProblemBuilder builder = createProblemBuilder(problem,request);
        builder.withCause(((DefaultProblem) problem).getCause())
                .withDetail(problem.getDetail())
                .withInstance(problem.getInstance());

        return new ResponseEntity<>(builder.build(), responseEntity.getHeaders(), responseEntity.getStatusCode());

    }
     
2.  And of the Shelf traits like below,we use constraint violation traits from API

            @Override
                public ResponseEntity<Problem> process(ResponseEntity<Problem> entity, 
              NativeWebRequest request) {
             Problem problem = entity.getBody();
            ProblemBuilder problemBuilder = createProblemBuilder(problem,request);
            if (problem instanceof ConstraintViolationProblem) {
                  problemBuilder
                    .with("violations", ((ConstraintViolationProblem) problem).getViolations());

             }
                 return new ResponseEntity<>(problemBuilder.build(), entity.getHeaders(),  
                 entity.getStatusCode());
                  }

 default ProblemBuilder createProblemBuilder(final Problem problem , final NativeWebRequest request) {

        ProblemBuilder builder = Problem.builder()
                .withStatus(problem.getStatus())
                .withTitle(problem.getTitle())
                .with("path", request.getNativeRequest(HttpServletRequest.class).getRequestURI());
        return builder;
    }

  
3.  We document it using Swagger as below  on controller

              @ApiResponses(value = {
            @ApiResponse(code = 200 , message = "xxxx", response = XXXXResponse.class ),
            @ApiResponse(code = 400 , message = "Bad Request", response = XXXError.class )
              })

 But now as we are using Traits for internal server and api traits ,we tried adding ProblemBuilder ,but as its contents are generated dynamically the content on swagger is Empty
    
 How is it done, or rather how should it be done when using Swagger ?

**Comment by smfaizalkhan** [comment]
@whiskeysierra 

Would like to know how to document the traits for the Swagger Documentation

**Comment by whiskeysierra** [comment]
At Zalando we follow an [*API First Principle*](https://opensource.zalando.com/restful-api-guidelines/#100) and the common approach that we use is to define the API upfront, by hand. That means we don't use any Swagger/OpenAPI schema generation tools.

If you craft it by hand you can reference the standard schema: https://opensource.zalando.com/restful-api-guidelines/#176

**Comment by cbornet** [comment]
@smfaizalkhan Have you tried `AbstractThrowableProblem.class` ?

**Comment by smfaizalkhan** [comment]
@whiskeysierra Thanks
@cbornet   Thanks for your suggestion 
  AbstractThrowableProblem.class 
         gives all its properties ,whereas we have application specific 
         error properties

**Comment by cbornet** [comment]
> ,whereas we have application specific
error properties

If these properties are set dynamically in the `parameters` field, then the annotation processor (springfox ?) has no way to know which are those fields.
If instead you  use a class that inherits from  ̀AbstractThrowableProblem`, then just use that class.
