### ISSUE TITLE
Add simpler support to convert HttpStatus to StatusType

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#42]
#31 already did all the hard work, but I saw the need to do the conversion once, manually:

```
Problem.valueOf(convert(status), "..");
```

**Comment by kakawait** [comment]
@whiskeysierra why not just changing `HttpStatusAdapter` scope to `public`

thus

```
Problem.valueOf(new HttpStatusAdapter(status), "..");
```

**Comment by kakawait** [comment]
I had the same issue when extending `ThrowableProblem` (it's more about `Problem` interface in fact) for custom exception

```
StatusType getStatus();
```

**Comment by whiskeysierra** [comment]
> Problem.valueOf(new HttpStatusAdapter(status), "..");

Possible, but I'd like something shorter, preferably a static factory method (I remember you proposed something like that.)

**Comment by kakawait** [comment]
yes this commit https://github.com/kakawait/problem-spring-web/blob/315efccd6d4e9b404f8a9538e2f8ce3e69825a67/src/main/java/org/zalando/problem/spring/web/advice/StatusConverter.java

**Comment by whiskeysierra** [comment]
Exactly.
