### ISSUE TITLE
Using starter creates an @Order conflict with OAuth2 ResourceServer security configuration

### ISSUE THREAD

**Issue by jdbranham** [zalando/problem-spring-web#426]
## Description
When using the problem-spring-web-starter library, and Spring's OAuth2 ResourceServer configuration, the `@Order` annotations collide.  
I saw documentation in the README about manually wiring up the security components, but I think that's when we don't use Spring Boot. Is that correct?
If not, maybe we could just clarify the documentation, that this is expected.  

## Expected Behavior
OAuth2 ResourceServer and Problem's SecurityConfiguration should load

## Actual Behavior
An exception is thrown by Spring because both classes have the same `Order`. 

@Order on WebSecurityConfigurers must be unique. Order of 100 was already used on org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerWebSecurityConfiguration$OAuth2WebSecurityConfigurerAdapter$$EnhancerBySpringCGLIB$$5714cc4b@2dc9e445, so it cannot be used on org.zalando.problem.spring.web.autoconfigure.security.SecurityConfiguration$$EnhancerBySpringCGLIB$$bca7d153@191df20e too.

## Possible Fix
I'm not sure of the fix yet, but as a workaround I use `problem-spring-web` and manually wire up the problem security components like this - 

```java
@Configuration
@Import(SecurityProblemSupport.class)
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    private final JwtDecoder jwtDecoder;
	private final SecurityProblemSupport problemSupport;
    
    public SecurityConfiguration(JwtDecoder jwtDecoder, SecurityProblemSupport problemSupport) {
    	this.jwtDecoder = jwtDecoder;
    	this.problemSupport = problemSupport;
	}

	@Override
    public void configure(HttpSecurity http) throws Exception {
        http.exceptionHandling()
        .authenticationEntryPoint(problemSupport)
        .accessDeniedHandler(problemSupport).and()
        .authorizeRequests()
                .antMatchers("/v3/api-docs",
                        "/swagger-resources/**",
                        "/swagger-ui.html",
                        "/webjars/**").permitAll()
                .anyRequest().authenticated()
                .and().cors().and().csrf().and()
                .oauth2ResourceServer().jwt().decoder(jwtDecoder);
    }
}
```

## Steps to Reproduce
Using this configuration produces the `@Order` collision.  
 
```java
@Configuration
public class SecurityConfiguration extends ResourceServerConfigurerAdapter {

    private final JwtDecoder jwtDecoder;
    
    public SecurityConfiguration(JwtDecoder jwtDecoder) {
    	this.jwtDecoder = jwtDecoder;
	}

	@Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .antMatchers("/v3/api-docs",
                        "/swagger-resources/**",
                        "/swagger-ui.html",
                        "/webjars/**").permitAll()
                .anyRequest().authenticated()
                .and().cors().and().csrf().and()
                .oauth2ResourceServer().jwt().decoder(jwtDecoder);
    }
}
```

## Context
Trying to use the problem autoconfiguration.

## Your Environment
Spring Boot v2.1.10.RELEASE
problem-spring-web-starter v0.25.0

**Comment by whiskeysierra** [comment]
@theHilikus is this related to #386?

**Comment by theHilikus** [comment]
@whiskeysierra most likely
@jdbranham please try the latest version 0.25.2. there was a bug fix exactly for that issue

**Comment by jdbranham** [comment]
Worked great. Thanks guys!
