### ISSUE TITLE
Public API JDK vanilla

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#44]
What do you think about the idea of exposing only (or at least) `JDK` _vanilla_ compliant API?

Example without using `ImmutableList` from `guava` or offer an alternative with `List`

**Comment by AlexanderYastrebov** [comment]
I personally strongly for it.
Maybe it even possible to get rid of guava completely.

**Comment by AlexanderYastrebov** [comment]
The rationale is that for small utility libraries one would like to have as less dependencies as possible

**Comment by kakawait** [comment]
There are three solutions from m'y point of view

1. Drop `guava` completely 
2. Rewrite `public` and `protected` api to only use standard object
3. Add new api in addition to existing one that not using standard object

About `guava` the only thing we could loose in term of functionality is `Immutable` collection. `JDK` only offers `unmodifiable` that quite different and less safe in term of immutability (in fact is not immutable)

What do you think about? Maybe other solutions...

**Comment by whiskeysierra** [comment]
I'd say 1). 

> About guava the only thing we could loose in term of functionality is Immutable collection. JDK only offers unmodifiable that quite different and less safe in term of immutability (in fact is not immutable)

True, but I think a defensive copy (maybe not even that, since we are in charge of that list) + unmodifiable should be enough.

**Comment by AlexanderYastrebov** [comment]
See #47

**Comment by AlexanderYastrebov** [comment]
The interesting part is that guava dependency is transitive from `problem` library

**Comment by AlexanderYastrebov** [comment]
See also https://github.com/zalando/problem/pull/28

**Comment by kakawait** [comment]
Could be close thanks to @AlexanderYastrebov  PR?

**Comment by whiskeysierra** [comment]
We still need to release it, but in theory yes.
