### ISSUE TITLE
Allow to set traceId in Problem.instance field

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [zalando/problem-spring-web#442]
## Detailed Description
We use problem-spring-web in our Spring Boot MVC based API to respect rfc7807 and would like to use instance field to set a traceId as defined by OpenTracing (https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md#b3-http-headers)

## Possible Implementation
The issue is that Problem.instance is settable only through builder.
And in org.zalando.problem.spring.web.advice.AdviceTrait.create(StatusType, Throwable, NativeWebRequest, HttpHeaders) org.zalando.problem.spring.common.AdviceTrait.toProblem(Throwable, StatusType) is called without a mean to get http header containing this traceId.

To fix that I suggest simply to pass request variable in parameter of AdviceTrait.toProblem() method call.

**Comment by whiskeysierra** [comment]
> would like to use instance field to set a traceId as defined by OpenTracing

`instance` is meant to be a URI reference. Also for OpenTracing, why not just use HTTP headers, as normally?

**Comment by whiskeysierra** [comment]
> org.zalando.problem.spring.common.AdviceTrait.toProblem(Throwable, StatusType) is called without a mean to get http header containing this traceId.

What if the original request didn't contain a trace id? Then you would create one locally and having access to the request wouldn't help much. You could just access the current active span and get the trace id from there.
