### ISSUE TITLE
Have Problem-spring-web aware of OAuth2Exception 

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [zalando/problem-spring-web#443]
## Detailed Description
In my HTTP/JSON API, when Spring throwing a InsufficientScopeException, subtype of OAuth2Exception, problem-spring-web give me a HTTP 500 code in status and resulting JSON while it should be a 401 http code.
This seems due that there is no SecurityAdviceTrait for OAuth2Exception  exceptions.

**Comment by whiskeysierra** [comment]
That's correct. But isn't spring security running as a filter before any
controller or controller advice and therefore would pass this code anyway?
How is this exception thrown in your case? From within your application?

**Comment by whiskeysierra** [comment]
OAuth2Exception is not part of spring-security (core) which means we would need another dependency for that and yet another optional additional advice trait.

For now you'd be better off by just implementing the necessary method within your controller advice:

```java
@ExceptionHandler
default ResponseEntity<Problem> handleOAuth2Exception(final OAuth2Exception e,
        final NativeWebRequest request) {
    return create(UNAUTHORIZED, e, request);
}
```
