### ISSUE TITLE
MessageNotReadableAdviceTrait not working for Spring v5.2.4.RELEASE

### ISSUE THREAD

**Issue by bpicode** [zalando/problem-spring-web#455]
Observed with Spring v5.2.4. Whenever a request body cannot be deserialized by failing with a JsonMappingException, the MessageNotReadableAdviceTrait does not get invoked.

## Description

I noticed this in a kotlin project, where a MissingKotlinParameterException was thrown. This exception should, in general, map to a 400 Bad Request with a problem description.

## Expected Behavior
A 400 Bad Request in the aforementioned case.

## Actual Behavior
In my case, a 500 Server Error was returned (generic fallback).

## Possible Fix

I noticed that MessageNotReadableAdviceTrait relies on a HttpMessageNotReadableException being thrown. With https://github.com/spring-projects/spring-framework/commit/b889700548681382911e06701b257549bb81e929 Spring throws a HttpMessageConversionException instead. One might fix this problem here by introducing another AdviceTrait handling such exceptions. Not sure however, if one should reach out to spring team instead.

## Steps to Reproduce

Maybe later, limited on time :(

## Context
See above.

## Your Environment

* Version used: 0.25.2

**Comment by whiskeysierra** [comment]
Related to https://github.com/spring-projects/spring-framework/issues/24610

**Comment by whiskeysierra** [comment]
Corresponding issue in Spring has been fixed.
