### ISSUE TITLE
Constraint Violation URL customization 

### ISSUE THREAD

**Issue by galvo** [zalando/problem-spring-web#472]
As per a previous issue https://github.com/zalando/problem-spring-web/issues/40 it would be beneficial to allow overriding the default Zalando Constraint Violation URL with a custom URL that is self-hosted.

## Context
Companies may want to provide further details on the constraint violation in the web page so it is beneficial for them to self-host this page themselves and also it looks more professional for developers interacting with the API's is a consistent URL's are provided.

**Comment by holgerstolzenberg** [comment]
Using your library and works great so far. Stumbled upon this one trying to implement relative problem URIs.

If discussing about that: Relative URIs for problems are recommend by your very own guidelines ([MUST use problem JSON [176]](https://opensource.zalando.com/restful-api-guidelines/#176)).

**Comment by galvo** [comment]
Zalando any thoughts on this?

**Comment by whiskeysierra** [comment]
In hindsight it was a mistake to add concrete problem types in this
library. There is very little benefit in sharing those across companies or
projects. I'd rather deprecate those that we have than changing them in
order to make them more useful.

**Comment by whiskeysierra** [comment]
I'm closing this for now (see my last comment). Feel free to continue discussing this and I will re-open, if necessary.
