### ISSUE TITLE
Validation, but not 422?

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#49]
In common case we used to validated entity from `POST`, `PUT`, etc.. Thus when validation exception is triggered the good way is to return `422 Unprocessable Entity` !

However sometime we can validate query param like following API:

```
/api/feed?url=XXX
```

Where `url` is mandatory param with following validation:

1. Should not be empty
2. Should be a valid URL

For 1. we can simply return a `MissingServletRequestParameterException` that is correctly manage by *problem-spring-web* but for 2. I don't think `422 Unprocessable Entity` is a correct status. Because url and query param is not part of request entity.

I was thinking about returning `400` status but with validation problem body

```
{
  "violations": [
    {
      "field": "url",
      "message": "must be a valid URL"
    }
  ],
  "type": "<URI>",
  "status": 400,
  "title": "Constraint Violation"
}
```

Do you think is a good idea? If yes how can I reuse existing `ConstraintViolationProblem` (`final` class)

**Comment by whiskeysierra** [comment]
Interestingly we had the same discussion internally a couple of days ago. We came down to the following two (conflicting) opinions:

- `400 Bad Request` should be used for syntax errors, e.g. invalid JSON while `422 Unprocessable Entity` is more about semantic errors
- The `URI` is not part of the request entity, therefore `422` does not apply

**Comment by kakawait** [comment]
I opened a stackoverflow (with 3th edge case about post validation) but I don't really like current answer http://stackoverflow.com/questions/37526199/post-condition-check-http-status

**Comment by whiskeysierra** [comment]
Would it be sufficient for you to introduce a property in `ConstraintViolationProblem` that allows to customize the status? Or would you vote for changing this to 400 globally?

**Comment by kakawait** [comment]
`422` is correct status when validating body, so global static value is not the way to go. So from my point of view I still prefer first proposal. Nevertheless I think `MethodArgumentNotValidException` still by default returns `422` and user should override or use other exception (like `BindException`) if he should want return `400`.

Question can also be reported to your (Zalando) *rest guideline*?

**Comment by whiskeysierra** [comment]
> Question can also be reported to your (Zalando) rest guideline?

Indeed.

**Comment by kakawait** [comment]
Because the end without clear standard (or de facto one) following issue can be not an issue depending on your guideline

**Comment by kakawait** [comment]
@whiskeysierra regarding recent discussion on https://github.com/zalando/restful-api-guidelines/issues/82 do you think is valide request? If you're ok with that I will try to PR something next week

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
We changed our guidelines to favor 400 over 422, see zalando/restful-api-guidelines#122

The next logical step would be to change the specification of https://zalando.github.io/problem/constraint-violation as well as the actual implementation.

**Comment by lukasniemeier-zalando** [comment]
> We changed our guidelines to favor 400 over 422, see zalando/restful-api-guidelines#122

The referenced issue zalando/restful-api-guidelines#82 is only talking about what to do with `GET` query parameters. Why should we change the specification of https://zalando.github.io/problem/constraint-violation?

**Comment by whiskeysierra** [comment]
Because 422 conceptually only applies to the request entity. Constraint
violations on the other hand could very well be used for the other parts of
the request as well.

Discussions in the Guild concluded in dropping support altogether in favor
of 400.

**Comment by kakawait** [comment]
But do you plan to allow status code customization for people that want to keep `422` over `400` or something else?

**Comment by whiskeysierra** [comment]
I'd say that should be easily possible by overriding the corresponding method, shouldn't it?

**Comment by kakawait** [comment]
if not `final` it will be ok

**Comment by whiskeysierra** [comment]
Everything is in the `AdviceTrait` interface, so it can't be final.
