### ISSUE TITLE
Upgraded to 0.25.2 - InsufficientAuthenticationException is now a 500 error

### ISSUE THREAD

**Issue by DanielHaughton** [zalando/problem-spring-web#498]
I upgraded from Spring boot 2.1.0 to 2.3.1 and problem-spring-web from 0.22.1 to 0.25.2.

I am now having issues where InsufficientAuthenticationException is being turned into a 500 error.

is this a library incompatibility problem? I see the master branch of problem-spring-web is built on Spring boot 2.3.2 , however it seems like there hasn't been a release since 2019?

If I back the version down to 0.23.0 it works fine

When I debug I can see that org.zalando.problem.spring.common.AdviceTrait the following lines of code

[    default ThrowableProblem toProblem(final Throwable throwable) {
        StatusType status = (StatusType)Optional.ofNullable(this.resolveResponseStatus(throwable)).map(ResponseStatusAdapter::new).orElse(org.zalando.problem.Status.INTERNAL_SERVER_ERROR);
        return this.toProblem(throwable, status);
    }

    @API(
        status = Status.MAINTAINED
    )
    default ResponseStatus resolveResponseStatus(final Throwable type) {
        ResponseStatus candidate = (ResponseStatus)AnnotatedElementUtils.findMergedAnnotation(type.getClass(), ResponseStatus.class);
        return candidate == null && type.getCause() != null ? this.resolveResponseStatus(type.getCause()) : candidate;
    }](url)

In resolveResponseStatus I can see the Throwable is the InsufficientAuthenticationException, I can see type.getCause is null, and candidate is null.

The InsufficientAuthenticationException is being caused by no token being sent, which was handled as a 401 fine before I upgraded

**Comment by whiskeysierra** [comment]
Are you using `SecurityAdviceTrait` directly or do you rely on the auto configuration?
