### ISSUE TITLE
Spring Security support

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#5]
Spring security, e.g. OAuth, produces its own error objects (at least this is what I see on our test services).

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by whiskeysierra** [comment]
It usually looks like one of the following errors (not sure what's the difference though):

    {
        "error": "unauthorized",
        "error_description": "An Authentication object was not found in the SecurityContext"
    }

    {
        "error": "unauthorized",
        "error_description": "Full authentication is required to access this resource"
    }

**Comment by lukasniemeier-zalando** [comment]
Top: there is no anonymous-user filter in your filter-chain but the requested path demands authentication
Bottom: there is an anonymous-user filter which assigned the ``anonymousUser`` principal to the request and the requested path demands authentication.

**Comment by whiskeysierra** [comment]
I guess this doesn't pass by the controller advice, right? In that case we should have a concept for exceptions/problems that need to be handled differently and/or elsewhere.

**Comment by lukasniemeier-zalando** [comment]
> I guess this doesn't pass by the controller advice, right?

Yep up to the specific security-implementation. See what Spring-OAuth2 does [here](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/error/AbstractOAuth2SecurityExceptionHandler.java#L59).

**Comment by whiskeysierra** [comment]
http://stackoverflow.com/questions/19767267/handle-spring-security-authentication-exceptions-with-exceptionhandler/26502321#26502321

**Comment by kakawait** [comment]
I will test that asap 👍
