### ISSUE TITLE
Problem Starter Autoconfig tries to configure spring security if starter is on path, even if excluded by @SpringBootApplication(excludes)

### ISSUE THREAD

**Issue by ddcruver** [zalando/problem-spring-web#507]
The problem-boot-starter autoconfiguration tries to configure spring security even it spring securities autoconfiguration is excluded in @SpringBootApplication annotation.

## Expected Behavior

It to not try to configure Spring Security if it is not enabled.

## Actual Behavior

It tries to use a bean that is not configured and this error is outputted and application terminates.

`
***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' that could not be found.
Action:
Consider defining a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' in your configuration.
Application terminated with exit code of 1. Container will now exit.
`

## Possible Fix

Make it conditional on another bean or check bean exists.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Spring Boot 2.2.7
* Link to your project:

**Comment by whiskeysierra** [comment]
Which auto configurations are you excluding?

**Comment by ddcruver** [comment]
`@SpringBootApplication(
		scanBasePackages = {
				"..."
		},
		exclude = {
				SecurityAutoConfiguration.class,
				ManagementWebSecurityAutoConfiguration.class
		})`

**Comment by whiskeysierra** [comment]
Our configuration only applies, if `WebSecurityConfiguration` was also configured. Are you sure your exclude are correct?

https://github.com/zalando/problem-spring-web/blob/f5630d5faf314dcd7ea742d3d286a61f60bad023/problem-spring-web-autoconfigure/src/main/java/org/zalando/problem/spring/web/autoconfigure/security/ProblemSecurityAutoConfiguration.java#L32

**Comment by ddcruver** [comment]
We are not using Spring Security right now so I removed the starter from our classpath and only kept the required dependencies (security-core) to keep the annotations on the classes (i.e. @PreAuth). The issue went away with that.  

I don't think we have a WebSecurityConfiguration bean and looking at your Configuration class it looks right to me as well.  I will close this unless someone can reproduce it and verify they don't have this bean in their context.
