### ISSUE TITLE
For zalando problem library Springboot version 2.2.2 stack trace disabling not working

### ISSUE THREAD

**Issue by bethuelmuchina** [zalando/problem-spring-web#514]
@Bean
    public Jackson2ObjectMapperBuilderCustomizer zalandoProblemJackson2ObjectMapperBuilderCustomizer() {
        return (Jackson2ObjectMapperBuilder jacksonObjectMapperBuilder) ->
                jacksonObjectMapperBuilder.modules(new ProblemModule().withStackTraces(false));
    }

**Comment by whiskeysierra** [comment]
Can you paste the json output?
