### ISSUE TITLE
toStatus and isCasualChainEnabled serialization

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#53]
When I was writing my own `ThrowableProblem` I had to implement 

```
Response.StatusType getStatus();
```

However to do not use *JaxRS* status I added `SpringAdviceTrait` implements on my custom `ThrowableProblem` in order to use 

```
default StatusType toStatus(HttpStatus status) {
    return new HttpStatusAdapter(status);
}
```

However by doing such thing my custom `ThrowableProblem` becomes an `AdviceTrait` and

```
isCausalChainsEnabled();
```

is serialized to the response.

```
{"causalChainsEnabled":false,"status":502,"type":"https://httpstatuses.com/502","detail":"Following upstream host \"httpbin.or\" is unknown","title":"Upstream host problem"}
```

---

Related to https://github.com/zalando/problem-spring-web/issues/42

Since `HttpStatusAdapter` is package scope there is no real alternative instead using *JaxRS*

**Comment by whiskeysierra** [comment]
That's definitely a problem (:wink:). Are you willing to open a pull request that makes the class public?

**Comment by kakawait** [comment]
Yes or can `JsonIgnore` that field

**Comment by whiskeysierra** [comment]
I think implementing SpringAdviceTrait in a custom problem is already a hack, and the current API forces you to do it. So we should get rid of it.

**Comment by kakawait** [comment]
I will push tomorrow. I don't have dev computer atm :)
