### ISSUE TITLE
Add an explanation for "throws HttpMediaTypeNotAcceptableException"

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem-spring-web#56]
Please add in the docs why it throws `HttpMediaTypeNotAcceptableException`, changes came with version `0.8.0`.

**Comment by lukasniemeier-zalando** [comment]
Why do we have the exception there at all? Is it just because we are using `HeaderContentNegotiationStrategyresolveMediaTypes`? If yes we may should think about catching this exception [here](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L150) and handle it like there were no `Accept` headers given.

**Comment by whiskeysierra** [comment]
But clients may declare that they need something specific that we can't provide,  e.g. `application/fancy-error+xml` or something. In that case we shouldn't just ignore it.

**Comment by lukasniemeier-zalando** [comment]
Sorry I was a bit unclear: don't handle it like "there were no `Accept` headers given", but like this:

```java
try {
    final List<MediaType> mediaTypes = negotiator.resolveMediaTypes(request);
} catch (final HttpMediaTypeNotAcceptableException e) {
    return Optional.empty();
}
```

I.e. handling it like we already do for no matching `Accept` content-type - what we already do with in `fallback`. Let's take the same code what for any `HttpMediaTypeNotAcceptableException`. After all this only happens in case there is a [malformed](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/accept/HeaderContentNegotiationStrategy.java#L57) content-type specified...

**Comment by whiskeysierra** [comment]
The fallback produces a ResponseEntity by default. Spring in turn tries to find a message converter for that based on the Accept header. So it will fail with the same exception again later down the road.
