### ISSUE TITLE
Simplest way to add the type information to every Problem?

### ISSUE THREAD

**Issue by JayChandler** [zalando/problem-spring-web#561]
It seems only on certain exceptions the type field will be set for instance ConstraintViolationException. It would be nice if there would be an easy way to create this informtion for every exception without the need of overwriting everything.

**Comment by whiskeysierra** [comment]
> "type" (string) - A URI reference [RFC3986] that identifies the
      problem type.  This specification encourages that, when
      dereferenced, it provide human-readable documentation for the
      problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
      this member is not present, its value is assumed to be
      "about:blank".
>
> https://tools.ietf.org/html/rfc7807#page-5

So the type is optional and there is no easy or obvious way dynamically generate something.

What would be your expectation?

**Comment by JayChandler** [comment]
> > "type" (string) - A URI reference [RFC3986] that identifies the
> > problem type.  This specification encourages that, when
> > dereferenced, it provide human-readable documentation for the
> > problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
> > this member is not present, its value is assumed to be
> > "about:blank".
> > https://tools.ietf.org/html/rfc7807#page-5
> 
> So the type is optional and there is no easy or obvious way dynamically generate something.
> 
> What would be your expectation?

For the constraint violation you have somehting like

` public static final String TYPE_VALUE = "https://zalando.github.io/problem/constraint-violation"`

Why not just use something like

` "https://zalando.github.io/problem/" + throwable.getClass().getSimpleName()` or provide a callback where an URI can be returned for a provblem?

**Comment by whiskeysierra** [comment]
> Why not just use something like
> 
> ` "https://zalando.github.io/problem/" + throwable.getClass().getSimpleName()` or provide a callback where an URI can be returned for a provblem?

I don't really see how that would add any value. The type should give you some additional information, on top of the status itself. Not only wouldn't that be the case, we would instead even leaking internals of the exception to problem/status mapping. As an example, multiple different exceptions map to `400 Bad Request` right now, but clients shouldn't need to deal with same translated java exception names in the type.

**Comment by whiskeysierra** [comment]
> provide a callback where an URI can be returned for a provblem?

That one might actually be useful.
