### ISSUE TITLE
Add maven-wrapper

### ISSUE THREAD

**Issue by c00ler** [zalando/problem-spring-web#57]
It might make sense to use maven-wrapper to simplify setup of the project.

**Comment by AlexanderYastrebov** [comment]
Hi. Do you mean this one https://github.com/takari/maven-wrapper
`problem-spring-web` is a lib, how maven wrapper can help?

**Comment by whiskeysierra** [comment]
I'm not sure why we actually require the version.

**Comment by lukasniemeier-zalando** [comment]
```
mvn -N io.takari:maven:wrapper && ./mvnw clean verify
...
[INFO] The Maven Wrapper has been successfully setup for your project.
...
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.3/apache-maven-3.3.3-bin.zip
...
[INFO] BUILD SUCCESS```

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando Do you suggest to use it like shown in your example?
