### ISSUE TITLE
@JSONProperty not read in ConstraintViolationProblem

### ISSUE THREAD

**Issue by PraveenGNair** [zalando/problem-spring-web#610]
I am using `problem-spring-web` and my contraint violations are not picking the fieldnames defined in @JSONProperty rather it is picking the deafult field name.

```
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonProperty;

@NotNull
@JsonProperty(destination_filename)
private String destinationFilename;
```
And I am getting an error as below when passing empty string through API.

```
{
  "type": "https://zalando.github.io/problem/constraint-violation",
  "status": 400,
  "violations": [
    {
      "field": "destinationFilename",
      "message": "must not be null"
    }
  ],
  "title": "Constraint Violation"
}
```

@whiskeysierra Is this a known issue ? or any worksarounds to pick the JSONProperty name in exception fieldname.

**Comment by whiskeysierra** [comment]
Fieldnames are provided by your bean validator (probably Hibernate). They can't be controlled via Jackson annotations.

**Comment by PraveenGNair** [comment]
Thanks. Though I got it [working](https://stackoverflow.com/a/66862426/7078558) by overriding `createviolation` method of `ValidationAdviceTrait`.
