### ISSUE TITLE
Functional controller for webmvc support

### ISSUE THREAD

**Issue by haupv1m** [zalando/problem-spring-web#614]
Functional controller for webmvc support

## Detailed Description
From Spring 5.2, the functional approach will also be available in the Spring Web MVC framework. Currently, i am using this approach. However, problem-spring-web currently support traditional annotation controller only. Do you have any plan for support mitigate to use with functional controller in spring MVC.

## Possible Implementation
- Support interface with function ServerRequest, ServerResponse and RouterFunctions functions

**Comment by whiskeysierra** [comment]
We're not using web functions (yet?), so it's not a priority. But you're more than welcome to contribute it.
