### ISSUE TITLE
Support RequestRejectedException

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#70]
Add support for `org.springframework.security.web.firewall.RequestRejectedException`, which is, for example, thrown by the `org.springframework.security.web.firewall.DefaultHttpFirewall` in case a non-normalized path is requested.

**Comment by whiskeysierra** [comment]
How would your expected problem look like?

**Comment by lukasniemeier-zalando** [comment]
I'd expect a standard `400 Bad Request`.

What I see is that those exceptions are thrown by the `DefaultHttpFirewall` in `org.springframework.security.web.FilterChainProxy`, so there is no obvious way on how to handle it.

**Comment by whiskeysierra** [comment]
So our trick with the [`ProblemAuthenticationEntryPoint`](https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/security/ProblemAuthenticationEntryPoint.java) doesn't work?

**Comment by lukasniemeier-zalando** [comment]
Yes execution does not seem to reach this point, exception is thrown [here](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/FilterChainProxy.java#L193), before the security filter even starts [here](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/FilterChainProxy.java#L208).

**Comment by whiskeysierra** [comment]
Any idea how to integrate it?

**Comment by lukasniemeier-zalando** [comment]
Maybe we should take a look at the error dispatch again... the guy maintaining `logbook` will hate us, that's sure :no_good_man:

**Comment by whiskeysierra** [comment]
Can I convince you that this doesn't require special support in problem-spring-web?

**Comment by atkawa7** [comment]
@whiskeysierra @lukasniemeier-zalando Please reopen this. It is thrown when api sends a wrong http verb. To solve must implement  `RequestRejectedHandler`
