### ISSUE TITLE
Support ValidationException

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#71]
What do we think of adding support for the base validation exception `ValidationException` as we already support one implementor `ConstraintViolationException`?

**Comment by whiskeysierra** [comment]
It doesn't provide any violations, does it?

**Comment by lukasniemeier-zalando** [comment]
No it's the base class for a set of validation problems. I am not sure if it is a good idea because some subclasses are for errors in the configuration of the validation.

**Comment by whiskeysierra** [comment]
What's your suggestion how we should handle it?

**Comment by lukasniemeier-zalando** [comment]
Looking again at all the subclasses I see no good reason to add it for now.
