### ISSUE TITLE
ProblemAuthenticationEntryPoint in spring-boot app

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/problem-spring-web#72]
Integrating the *ProblemAuthenticationEntryPoint* as described in the [README](https://github.com/zalando/problem-spring-web#security) leads to the following exception on starting a [*spring-boot* application](https://github.com/spring-guides/gs-securing-web/tree/master/complete):

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field resolver in org.zalando.problem.spring.web.advice.security.ProblemAuthenticationEntryPoint required a single bean, but 2 were found:
        - errorAttributes: defined by method 'errorAttributes' in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration.class]
        - handlerExceptionResolver: defined by method 'handlerExceptionResolver' in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Which one to pick?

**Comment by kakawait** [comment]
Same issue!

**Comment by lukasniemeier-zalando** [comment]
Excluding the `ErrorMvcAutoConfiguration` should mitigate the issue, but then you loose the error dispatch I assume.

**Comment by kakawait** [comment]
I just create my own `ProblemAuthenticationEntryPoint` with *qualified* name as workaround

**Comment by lukasniemeier-zalando** [comment]
@whiskeysierra what do you think of this as a work-around?

**Comment by whiskeysierra** [comment]
Adding a `@Qualifier("handlerExceptionResolver")` would also work, right?

**Comment by kakawait** [comment]
Yes it should but why using qualifier when you can use full qualified name variable?

**Comment by whiskeysierra** [comment]
Using a qualifier is always more expressive and more importantly it's safe against refactorings, especially accidental ones.

**Comment by kakawait** [comment]
> Using a qualifier is always more expressive and more importantly it's safe against refactorings, especially accidental ones.

Maybe, but if we really want to be safe we should create kind of *integration test* against small `Spring boot` app

**Comment by 0013461737** [comment]
@Bean
    @Qualifier("customResolver")
    HandlerExceptionResolver resolver() {
      DefaultHandlerExceptionResolver resolver = new DefaultHandlerExceptionResolver();
      resolver.
      resolver.setOrder(Ordered.HIGHEST_PRECEDENCE);
      return resolver;
    }

i wrote my custom handler
