### ISSUE TITLE
Hide technical details in answer but log them

### ISSUE THREAD

**Issue by arey** [zalando/problem-spring-web#721]
## Detailed Description

In 2021, this is the second time that an external company specializing in security is reporting during a pentest a security breach because the REST API response includes technical details.
Both Spring Boot applications  are using the `problem-spring-web-starter` module with no particular configuration.

## Context
In our GET API, a wrong date `2021-13-16` (month at `13`) is passed as query param. The `handleTypeMismatch` method of the `TypeMismatchAdviceTrait` class is invoked. 
A hacker can guess the technical stack: Java, Spring Framework, Bean Validation and Swagger in the case bellow.
```
{
  "title": "Bad Request",
  "status": 400,
  "detail": "Failed to convert value of type 'java.lang.String' to required type 'java.time.LocalDate'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@io.swagger.annotations.ApiParam @javax.validation.Valid @org.springframework.web.bind.annotation.RequestParam @org.springframework.format.annotation.DateTimeFormat java.time.LocalDate] for value '2021-13-16'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2021-13-16]"
}
```

## Possible Implementation
We woud like to have the possibility either to mask class or packages names in the details message that is returned to the client or to use a generic tehnical message.

We have to keep the real technical details in the ERROR log (`AdviceTraits::log`)

Other way: maybe using an overridable method to build the problem body on demand?
```
ResponseEntity
        .status(status)
        .headers(headers)
        .contentType(contentType)
        .body(problem))
```

## Your Environment

* Problem version used:  0.26.2
* Spring Boot version : 2.5.2

**Comment by whiskeysierra** [comment]
> Other way: maybe using an overridable method to build the problem body on demand?

Yes, there is:

https://github.com/zalando/problem-spring-web/blob/e7eb96a12da5400a3be6e64effd1194d231e7118/problem-spring-common/src/main/java/org/zalando/problem/spring/common/AdviceTrait.java#L66-L76

**Comment by arey** [comment]
Right, but the `prepare` method is called before the `log` one.

**Comment by whiskeysierra** [comment]
Correct, but `log` uses the original `throwable` instead of the constructed `problem`.

**Comment by arey** [comment]
Yes I see that. Thank you for the tipis. So I quickly fixed my issue with the code below (without this we got a nogo in production):
```
    @Override
    public ProblemBuilder prepare(final Throwable throwable, final StatusType status, final URI type) {
        BusinessException businessException = ExceptionUtils.throwableOfType(throwable, BusinessException.class);
        String detail = (businessException != null) ? businessException.getMessage() : "Technical error";
        return Problem.builder()
            .withType(type)
            .withTitle(status.getReasonPhrase())
            .withStatus(status)
            .withDetail(detail)
            .withCause(Optional.ofNullable(throwable.getCause())
                .filter(cause -> isCausalChainsEnabled())
                .map(this::toProblem)
                .orElse(null));
    }
```
I don't know if I am the only developer having this kind of security problem? How do you handle it?

**Comment by whiskeysierra** [comment]
We handle the translation of business exceptions in between the HTTP and domain layer.
With regards to the technical error message exposing to much details about the stack, for internal APIs that's not really a concern for us. Public APIs are guarded by authentication and authorization, i.e. you need to be a known entity before you can interact with any kind of backend.

**Comment by arey** [comment]
Our API are secured with OIDC and a JWT token but could be called from an Angular or React client. I hope that we do not have the same security report for private API. Thank you again @whiskeysierra  for your answer.

**Comment by HJK181** [comment]
@arey I do have the same problem after a pentest and stumbled open this issue.
I tried to solve it the same way, but the `prepare` method is not called in my case. I have the following controller advice
```
@ControllerAdvice
public class ExceptionTranslator implements ProblemHandling, SecurityAdviceTrait {
....
  @Override
  public ProblemBuilder prepare(Throwable throwable, StatusType status, URI type) {
    // never executed on Constraint Violation
  }
}
```
I do get the same error as you
```
{
  "type": "https://zalando.github.io/problem/constraint-violation",
  "title": "Constraint Violation",
  "status": 400,
  "violations": [
    {
      "field": "from",
      "message": "Failed to convert value of type 'java.lang.String' to required type 'java.time.LocalDate'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.format.annotation.DateTimeFormat java.time.LocalDate] for value '2022-05-asd'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [2022-05-asd]"
    }
  ],
  "message": "error.validation"
}
```
and yonder how you could fix it with that override? Somewhere in other issues, I've read that the prepare method is not called when the exception is already an `Problem` instance, which seams to be true!?

**Comment by arey** [comment]
Hi @HJK181 
Yes, I have overrided the `prepare` method into a `@ControllerAdvice` implementing both the `ProblemHandling` and the `SecurityAdviceTrait ` interfaces, like you.
This fix lives in the production environment and the pentester has approved it in pre-production.
At the end of the  `prepare`  method, I've added an incident number to facilitate the research the stacktrace with ELK and Splunk.
I don't know why in your case this `prepare` method is not called. 
This kind of  Spring exception are working in my case: `MethodArgumentTypeMismatchException` wrapping a `ConversionFailedException`
I'm using the `0.26.2` version of `problem-spring-web-starter`.

**Comment by HJK181** [comment]
Hi @arey 
Thanks for your response. Meanwhile, I debugged a little bit more and I think my problem is caused by `@DateTimeFormat(iso = ISO.DATE)` annotation of my `DTO` this causes 
```
org.springframework.core.convert.ConversionFailedException: Failed to conv'
ert from type [java.lang.String] to type [@org.springframework.format.annotation.Da'
teTimeFormat java.time.LocalDate]
```
This exception gets handled by `MethodArgumentNotValidAdviceTrait` that created a `newConstraintViolationProblem` and in that flow the `prepare` method is not called. Guess I could try to add an `@ExceptionHandler` for `ConversionFailedException` and discard the `Violation` message there.
