### ISSUE TITLE
Auto-configure not working when using @SpringBootApplication

### ISSUE THREAD

**Issue by echoesbr** [zalando/problem-spring-web#777]
## Description
The library is not initialised when using the annotation `@SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class)`

## Expected Behavior
The expected behaviour should be the default error response from the library.

## Actual Behavior
The default Spring boot response is returned (empty).

## Steps to Reproduce
1. Added library
`<dependency>
        <groupId>org.zalando</groupId>
        <artifactId>problem-spring-web-starter</artifactId>
        <version>0.27.0</version>
</dependency>`

2. Configure Spring boot
` web:
      resources:
        add-mappings: false
   mvc:
    throw-exception-if-no-handler-found: true`

3. Used annotation
`@SpringBootApplication(exclude = ErrorMvcAutoConfiguration.class)`

4. Alternatively tried with following without success
`@EnableAutoConfiguration(exclude = {ErrorMvcAutoConfiguration.class})
@Configuration
@ComponentScan(basePackages = "com.foo.bar")
@SpringBootConfiguration`

## Your Environment
* Version used: 0.27.0
* Spring Boot version: 2.6.6

**Comment by echoesbr** [comment]
Realised that my application already had a `@ControllerAdvice` class, so the one from the library was not being instantiated. Maybe worth mentioning in the docs.

**Comment by rafaelpontezup** [comment]
I had the same issue 😖

I have to be honest, I'm still not sure if I must configure `@EnableAutoConfiguration` when using the `problem-spring-web-starter` on `pom.xml`.

When I add the following config:
```java
@EnableAutoConfiguration(exclude = ErrorMvcAutoConfiguration.class)
```

And there's any `@ControllerAdvice` in the application, like this one:
```java
@ControllerAdvice
public class ResponseStatusExceptionHandler implements ResponseStatusAdviceTrait {

    @Override
    public ProblemBuilder prepare(Throwable throwable, StatusType status, URI type) {
        ResponseStatusException exception = (ResponseStatusException) throwable;
        return Problem.builder()
                .withTitle(status.getReasonPhrase())
                .withStatus(status)
                .withDetail(exception.getReason())
                ;
    }
}
```

Everything stopped working.

But if a disable the `ResponseStatusExceptionHandler` (like commenting the annotation out) everything works again!

Could you guys give us any help?
