### ISSUE TITLE
Confused to disable or able stack traces

### ISSUE THREAD

**Issue by MossLwj** [zalando/problem-spring-web#779]
## Description

I create a new project and test how to disable the stack traces. But i find that is invalid for the result. Look at the gif pic.I set the isCausalChainsEnabled false. but the response include the stack traces.
![Error](https://user-images.githubusercontent.com/28034235/164263034-85284ed0-9199-499a-8a55-b0946a0a1a64.gif)
Then i find that if i make the mvc config enable. the response will be include stack traces. When i disable the mvc config that will not include. look at the picture below
![Error2](https://user-images.githubusercontent.com/28034235/164265192-ec1f4790-1fa5-4018-8dde-93d95f36b367.gif)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
      <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>problem-spring-web-starter</artifactId>
            <version>0.27.0</version>
        </dependency>

* Link to your project:

**Comment by whiskeysierra** [comment]
You're using a custom Jackson ObjectMapper and the required modules are not
registered on it. I can tell because that JSON format is not a
problem-json, but just the default behaviour of Jackson.
