### ISSUE TITLE
Make Violation non-final

### ISSUE THREAD

**Issue by MrBuddyCasino** [zalando/problem-spring-web#782]
We would like to extend the `org.zalando.problem.violations.Violation` class to add more details about the violation and show them in the frontend, but this is currently impossible because the class is final. Consider using an interface or making the class extensible.

**Comment by whiskeysierra** [comment]
That's not what this problem type is meant for. Please see https://opensource.zalando.com/problem/constraint-violation/

> It’s **not** meant to be used for end-user input validation, but for client developer convenience.

**Comment by MrBuddyCasino** [comment]
> Any constraint violation problem happening in production should be considered a bug.

Even if one has the luxury of sufficient frontend engineer resources (we don't), that may be a Zalando design principle but I don't quite see why a generic Problem converter lib needs to enforce this. There is literally zero downsides to make a class non-final to interested parties, Zalando can still do what it wants internally. It only makes customisation much more intrusive.

**Comment by whiskeysierra** [comment]
> There is literally zero downsides to make a class non-final

Without going to much into details, I'm just gonna leaves this here:

- https://medium.com/@rufuszh90/effective-java-item-16-favour-composition-over-inheritance-ed82e482fd1a
- https://dzone.com/articles/problems-with-inheritance-in-java
