### ISSUE TITLE
Extensions to all problem types?

### ISSUE THREAD

**Issue by ralf-ueberfuhr-ars** [zalando/problem-spring-web#786]
## Detailed Description
Is it possible to easily extend problem objects by custom parameters?  Currently, the only way I found out was to overwrite the most central method that is invoked by hopefully all other exception handlers, and there create a copy of the problem instance, supplemented by the additional information.

```java
@ControllerAdvice
public class GlobalExceptionHandler implements ProblemHandling {

    @SuppressWarnings("NullableProblems")
    @Override
    public ResponseEntity<Problem> create(final Throwable throwable, final Problem problem, final NativeWebRequest request, final HttpHeaders headers) {
        // parameters are unmodifyable, so we need to copy the whole problem
        final var requestId = ...;
        final var problemWithRequestId = ProblemUtility.from(problem)
          .with("request_id", requestId)
          .build();
        return ProblemHandling.super.create(throwable, problemWithRequestId, request, headers);
    }
}
```

with the utility class

```java
public final class ProblemUtility {

    private ProblemUtility() {
    }

    public static ProblemBuilder from(Problem problem) {
        final ProblemBuilder result = Problem.builder();
        if (null != problem) {
            result
              .withStatus(problem.getStatus())
              .withDetail(problem.getDetail())
              .withInstance(problem.getInstance())
              .withTitle(problem.getTitle())
              .withType(problem.getType());
            problem.getParameters().forEach(result::with);
            if (problem instanceof ThrowableProblem) {
                result.withCause(((ThrowableProblem) problem).getCause());
            }
            if (problem instanceof ConstraintViolationProblem) {
                result.with("violations", ((ConstraintViolationProblem) problem).getViolations());
            }
        }
        return result;
    }

}
```

### The hurdles:
- There are currently two problem types (DefaultProblem and ConstraintViolationProblem) to be aware of.
- These problem types are immutable. So I would need to intervene into the Problem instance creation, which is ugly (see my code above)
- Both points IMHO could lead to issues in the future when other problem types are added.

## Context
I have an infrastructure that sets a REQUEST_ID header, and I want this to be placed as a parameter of the problem object in case of any error.

## Possible Implementation
It would be helpful just to define an interface as shown below and let me declare one or multiple Spring beans of this type - and read it out at the central positions in your code (You create a `ProblemBuilder` and let the bean add custom information to the builder).

```java
@FunctionalInterface
public interface ProblemInterceptor {
  void intercept(Throwable throwable, ProblemBuilder builder, NativeWebRequest request, HttpHeaders headers);
}
```

## Your Environment

* Version used: 0.27.0 of problem-spring-web

**Comment by whiskeysierra** [comment]
There is no single code path that let's you add properties to all problem types.
You'd need to deal with two kinds of problems separately:
1. [Generic problems](https://github.com/zalando/problem#generic), those are created by the advice traits directly, based on an exception. You can hook into the creation by overriding...
2. [Custom problems](https://github.com/zalando/problem#custom-problems) those are passed to Jackson as-is. You'd need to modify them before throwing.

Alternatively, you take a look into Jackson and try to find a way to hook into the serialization process to add a property on the fly. That approach is obviously out of scope for this library.
