### ISSUE TITLE
Faux-pas causes convergence error on code scanning tools

### ISSUE THREAD

**Issue by olgunkaya** [zalando/problem-spring-web#788]
Dependency convergence problem  caused by faux-pas
## Description
28-SNAPSHOT has dependency to faux-pas 0.9.0 and it has dependency to apiguardian-api 1.1.1. 
Also problem-spring-web itself has dependency to apiguardian-1.1.2.
As logged out below maven can resolve this by omitting the version 1.1.1 for apiguardian-api with reason of conflict. Still some tools are not ready for it.

```
[INFO] +- org.zalando:problem-spring-web:jar:0.27.0:compile
....
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.1.2:compile
.....
[INFO] |  |  +- (org.apiguardian:apiguardian-api:jar:1.1.1:compile - omitted for conflict with 1.1.2)
....
```

## Expected Behavior
faux-pas to has dependency to apiguardian-api 1.1.2 for zalando wide consistency.

## Actual Behavior
parent and sub dependencies has conflicting dependencies for apiguardian-api 1.1.1 and 1.1.2

## Possible Fix
update faux-pas dependency to 0.10.0

## Steps to Reproduce

1. create a spring boot project.
2. include zalando's problem-spring-web dependency
3. checkout dependency tree with -Dverbose
4. logs will show different dependencies (even if the dependency already omitted and not included in the final bundle)

## Context
fortify code scanning failing because of this. 

## Your Environment

* Version used: problem-spring-web version : 0.27.0
* Link to your project: N/A

**Comment by whiskeysierra** [comment]
> Still some tools are not ready for it.

There are tools that still get this basic concept of Maven dependency management wrong? 👀

**Comment by whiskeysierra** [comment]
I see those tools at fault, but if this is solved by upgrading some dependencies here and there, then I'm more than happy to merge some pull requests and trigger some releases.

**Comment by olgunkaya** [comment]
My bad, I thought faux-pas 0.10.0 released which is just a snapshot now. I'll check 0.10.0 release and issue a pull request (if zalando does not do it automatically or somehow not planned) once it's ready.
