### ISSUE TITLE
Problem with disabling stacktrace

### ISSUE THREAD

**Issue by sta-szek** [zalando/problem-spring-web#83]
My code is:
```
@Configuration
public class ProblemJsonConfiguration {
    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper().registerModule(new ProblemModule().withStackTraces(false));
    }
}
```

```
@ControllerAdvice
public class ExceptionHandler implements ProblemHandling { ... }
```

and response always contains field `stackTrace`:
```
{
  "cause": null,
  "stackTrace": [
    {
      "methodName": "resolveArgument",
      "fileName": "AbstractNamedValueMethodArgumentResolver.java",
      "lineNumber": 123,
      "className": "org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver",
      "nativeMethod": false
    },...
  ],
  "type": "about:blank",
  "title": "Bad Request",
  "status": "BAD_REQUEST",
  "detail": "Failed to convert value of type [java.lang.String] to required type ...",
  "instance": null,
  "parameters": {},
  "message": "Bad Request: Failed to convert value of type [java.lang.String] to required type ...",
  "localizedMessage": "Bad Request: Failed to convert value of type [java.lang.String] to required type ...",
  "suppressed": []
}
```

I followed steps on https://github.com/zalando/problem-spring-web/blob/master/README.md#stack-traces-and-causal-chains

Tried this:

```
@ControllerAdvice
class ExceptionHandling implements ProblemHandling {
    @Override
    public boolean isCausalChainsEnabled() {
        return false;
    }
}
```

and this: `server.error.include-stacktrace=NEVER`

There is no way to disable stactTrace. Am I doing something wrong?

BTW, 
Is there possibility to rename and disable some fields?

**Comment by whiskeysierra** [comment]
Stack traces and causal chaines are disabled by default, so you don't need to deal with them at all, in your case. Regarding your issue, I'm pretty certain that your ObjectMapper is not used. If you're using Spring Boot I'd suggest to rename the method to `jacksonObjectMapper`. Alternatively you need to configure your HttpMessageConverters manually.

**Comment by whiskeysierra** [comment]
References:

- [`jacksonObjectMapper`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L91)
- [`WebMvcConfigurerAdapter`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.html) to customizer message converters

**Comment by sta-szek** [comment]
Thanks, that was my problem. I have overriden `WebMvcConfigurerAdapter.configureMessageConverters(...)` method, so wrong `ObjectMapper` instance was taken. Thanks

**Comment by rajatul26** [comment]
I was also facing the same issue with Spring boot(2.0.2.RELEASE) MVC based application. If you are extending WebMvcConfigurerAdapter or implementing WebMvcConfigurer interface to customize the default behaviour just override the configureMessageConverters method of the same by adding the following code.

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        log.debug("Configuring custom HttpMessageConverters.");
        ObjectMapper mapper = Jackson2ObjectMapperBuilder.json()
                .modules(new ProblemModule(), new ConstraintViolationProblemModule()).build();

        converters.add(new MappingJackson2HttpMessageConverter(mapper));
    }


It worked for me.

Thanks

**Comment by theHilikus** [comment]
I also had to do what @kschulst mentioned to make a very simple dummy project work. It looks to me that that should be in the documentation instead of the two `@Bean` methods to return the two jackson modules

**Comment by whiskeysierra** [comment]
If the version with two beans doesn't work than that's an issue with spring itself.

**Comment by TRUSTMEIMJEDI** [comment]
```
@Configuration
public class ProblemJsonConfiguration {
    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper().registerModule(new ProblemModule().withStackTraces(false));
    }
}
```

Is enough ti mark bean as @Primary
