### ISSUE TITLE
BindException validation built-in support

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#85]
I would discuss with you if `org.springframework.validation.BindException` could be a great candidate to be a built-in managed exception.

Indeed when you're validating query params rather than post body like following

```java
@RequestMapping(path = "/handler-invalid-query-strings", method = GET)
public ResponseEntity<String> validRequestQueryStrings(@Valid final PageRequest pageRequest) {
    return ResponseEntity.ok("done");
}
```

With `PageRequest` looks like

```java
@Data
public final class PageRequest {

    @Min(value = 0)
    private int page = 0;

    @Min(value = 1)
    private int size = 50;
}
```

If you try

```java
@Test
public void invalidRequestQueryParams() throws Exception {
    mvc().perform(request(GET, "http://localhost/api/handler-invalid-query-strings?page=-1"))
         .andExpect(status().isBadRequest());
}
```

I will fail because `500` status code will be returned after Spring will throw `org.springframework.validation.BindException`

---

A bit off-topic, but can explain why:

 Spring `MethodValidationPostProcessor` works great with `zalando:problem-spring-web`, indeed if you replace previous `GetMapping` with following:

```java
@RequestMapping(path = "/handler-invalid-query-strings", method = GET)
public ResponseEntity<String> validRequestQueryStrings(@Min(value = 0) @RequestParam(value = "page", defaultValue = "0") int page,
        @Min(value = 1) @RequestParam(value="limit", defaultValue = "50") int limit) {
    return ResponseEntity.ok("done");
}
```

I will work but since method parameter **name is removed after compilation** the result looks like:

```json
{  
   "violations":[  
      {  
         "field":"getUsers.arg0",
         "message":"must be greater than or equal to 0"
      }
   ],
   "status":400,
   "type":"https://zalando.github.io/problem/constraint-violation",
   "title":"Constraint Violation"
}
```

As you can see `field` is equals to `getUsers.arg0` which is no really user-friendly.
That why I used to create a intermediate object (`DTO`?) for validation even for `GET` parameters.

**Comment by whiskeysierra** [comment]
> I will work but since method parameter name is removed after compilation

There are actually two different solutions to this issue:
1. JDK <= 1.7: compile with debug information, that will include parameter names and spring should be able to read them
2. JDK >= 1.8: compile with `-parameters`

Regardless of those two options I still like to have support for `BindException`.

**Comment by kakawait** [comment]
I didn't know that trick. Thank you for that I will try it tomorrow.

For `BindException` i don't think i will find time to PR before the end of the year. I will do it for 2017 :)

**Comment by kakawait** [comment]
@whiskeysierra did you ever try `-parameters` `javac` compiler option on jdk8?

I just add it but get the same result

```
"field":"getUsers.arg0"
```

**Comment by kakawait** [comment]
After some investigation I'm sure that `-parameters` is correctly set and working.

On `org.springframework.validation.beanvalidation.MethodValidationInterceptor` when I check `methodToValidate.getParameters()` with `-parameters` I have 

```
result = {Parameter[2]@9987} 
 0 = {Parameter@9989} "int page"
 1 = {Parameter@9990} "int limit"
```

and without 

```
result = {Parameter[2]@9545} 
 0 = {Parameter@9547} "int arg0"
 1 = {Parameter@9548} "int arg1"
```

I will continue to determine why and where Spring get `field` name

**Comment by kakawait** [comment]
I will stop flooding :)

I found the solution, I have to change my configuration from

```java
@Configuration
public class ValidationConfiguration {
    @Bean
    public MethodValidationPostProcessor methodValidationPostProcessor() {
        return new MethodValidationPostProcessor();
    }
}
```

to 

```java
@Configuration
public class ValidationConfiguration {

    @Bean
    public Validator validator() {
        return new LocalValidatorFactoryBean();
    }

    @Bean
    public MethodValidationPostProcessor methodValidationPostProcessor() {
        MethodValidationPostProcessor methodValidationPostProcessor = new MethodValidationPostProcessor();
        methodValidationPostProcessor.setValidator(validator());
        return methodValidationPostProcessor;
    }
}
```

In order to enable `StandardReflectionParameterNameDiscoverer`

Now I have 

```json
{  
   "violations":[  
      {  
         "field":"getUsers.page",
         "message":"must be greater than or equal to 0"
      }
   ],
   "status":400,
   "type":"https://zalando.github.io/problem/constraint-violation",
   "title":"Constraint Violation"
}
```

**Comment by whiskeysierra** [comment]
> @Bean
>     public Validator validator() {
>         return new LocalValidatorFactoryBean();
>     }

Ah, I remember that also always do this.

> If you are ok it can be added somewhere on documentation?

:+1:

**Comment by kakawait** [comment]
@whiskeysierra about doc do you really think that edge case should be part of `README.md`. From my point of view `README.md` should be an overview of the application/library/framework.

Maybe just I can just create an issue to describe the problem (different from `BindException` support) and close it, thus using issue tracking like a kind of *Q&A*?

**Comment by whiskeysierra** [comment]
I could also imagine to put this into the javadoc of the `ConstraintViolationAdviceTrait`.
