### ISSUE TITLE
Remove guava from dependencies

### ISSUE THREAD

**Issue by kakawait** [zalando/problem-spring-web#88]
Since https://github.com/zalando/problem-spring-web/issues/44 `guava` has been removed from public API signature.

Today `guava` is only used at https://github.com/zalando/problem-spring-web/blob/master/src/main/java/org/zalando/problem/spring/web/advice/AdviceTrait.java#L132

`Guava` is **2.3mb** jar size, **maybe we could consider remove it completely** and replace `firstNonNull()` with something else.

For any bandwidth saved we save a polar bear somewhere 🐻 

![image](https://cloud.githubusercontent.com/assets/275609/21591976/9489eb92-d109-11e6-9a0d-a102dc868a9a.png)

PS: Happy new year 🎉

**Comment by whiskeysierra** [comment]
I release [0.16.0](https://github.com/zalando/problem-spring-web/releases/tag/0.16.0).
