### ISSUE TITLE
package org.zalando.problem.jackson does not exist

### ISSUE THREAD

**Issue by mityakoval** [zalando/problem-spring-web#886]
After the update to 0.28.0 the `ProblemModule` class is gone along with the `jackson` package.
Where was it moved? If it was removed what should be used instead? 
The [readme](https://github.com/zalando/problem-spring-web/blob/main/problem-spring-web/README.md) still mentions, but it's impossible to configure the `ObjectMapper` in the way describe in the readme.

**Comment by blzsvass** [comment]
Hey,
I noticed that as well, you should explicitly import `jackson-datatype-problem` .
The class itself is here: https://github.com/zalando/problem/blob/main/jackson-datatype-problem/src/main/java/org/zalando/problem/jackson/ProblemModule.java

See the Installation instruction part in the readme: https://github.com/zalando/problem

**Comment by MALPI** [comment]
I think this should be fixed with #885. We are preparing the release right now.

**Comment by MALPI** [comment]
See https://github.com/zalando/problem-spring-web/releases/tag/0.29.1.

**Comment by HJK181** [comment]
@MALPI This seems to fix it only when one uses the auto-configuration module. However, in my project, I'm just using
```
  <dependency>
      <groupId>org.zalando</groupId>
      <artifactId>problem-spring-web</artifactId>
      <version>${problem-spring-web.version}</version>
  </dependency>
  <dependency>
      <groupId>org.zalando</groupId>
      <artifactId>problem-spring-webflux</artifactId>
      <version>${problem-spring-web.version}</version>
  </dependency>
```
This used to work prior to 0.28.0. Starting from 0.28.0, including 0.29.1 this fails as described in this issue.

**Comment by cberg-zalando** [comment]
It is due to the other projects defining the dependency as optional. It was not intended for users to require the Jackson dependency explicitly, so in this case we need to remove the optional there as well in order that it is transitively pulled in.

**Comment by cberg-zalando** [comment]
Looks like this is more complex: So neither the `problem-spring-web` nor the `problem-spring-webflux` dependency need the `ProblemModule` explicitly. It is just that the README file mentions it, which creates this situation. As Spring is in principle JSON library agnostic, even though most users will just use Jackson, we will update the README file so that the example code actually works.
