### ISSUE TITLE
ProblemModule Not found in latest version !!

### ISSUE THREAD

**Issue by 1udaypatil1** [zalando/problem-spring-web#911]
org.zalando.problem.jackson.ProblemModule
This is not present in latest release, which package has this been moved to ?
Or If this is removed what is used for Module for serialization/deserialization of RFC7807 Problem ?

**Comment by cberg-zalando** [comment]
Duplicate of #886. We updated the README of the `problem-spring-web` module, see #904 and https://github.com/zalando/problem-spring-web/tree/main/problem-spring-web#webmvc.

**Comment by 1udaypatil1** [comment]
Thanks for pointing that out.

**Comment by dsantospaytrix** [comment]
Hi @cberg-zalando i followed the steps you mentioned and i still can't see the ProblemModule. any ideas?
![Screenshot 2023-05-03 171932](https://user-images.githubusercontent.com/120374975/235977880-5af16b36-0db9-44ce-bee7-e2e3c54aa6e6.png)

my maven config:
`<dependency>
                <groupId>org.zalando</groupId>
                <artifactId>problem-spring-webflux</artifactId>
                <version>${zalando-problem-spring.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apiguardian</groupId>
                        <artifactId>apiguardian-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.zalando</groupId>
                <artifactId>problem-spring-web-starter</artifactId>
                <version>${zalando-problem-spring.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apiguardian</groupId>
                        <artifactId>apiguardian-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.google.code.findbugs</groupId>
                        <artifactId>jsr305</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.zalando</groupId>
                <artifactId>jackson-datatype-problem</artifactId>
                <version>${zalando-jackson-datatype-problem.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apiguardian</groupId>
                        <artifactId>apiguardian-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>`
