### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by nilsonfreitas** [zalando/problem-spring-web#94]
This library does EXACTLY what I am looking for but my app is deployed on [GAE Standard Environment](https://cloud.google.com/appengine/docs/java/runtime) and it doesn't support java 8.

In order to use [problem-spring-web](https://github.com/zalando/problem-spring-web), I will have to fork the repository + [problem](https://github.com/zalando/problem), make both compatible with my env and then start using it.

Do you have any advice for me before I get started? Are you planning to support java 7 on the near future?

Thanks

**Comment by AlexanderYastrebov** [comment]
I would say Java 7 in a past, not future :)
https://java.com/en/download/faq/java_7.xml

**Comment by whiskeysierra** [comment]
> I would say Java 7 in a past, not future :)

Not only that, but the whole idea of the project heavily relies on Java 8 language features, i.e. default methods in interfaces.
